### ISSUE TITLE
Uncaught TypeError: Cannot read property '[path_to_file]' of undefined

### ISSUE THREAD

**Issue by djpowers** [yongkangchen/atom-ctags#101]
1. View a file in Atom that does not have a `.tags` file
2. Press `CMD + R` to bring up symbol search which shows "Generating symbols..."
3. Error appears. Subsequent actions do not trigger error, after `.tags` file is created.

Can be reliably reproduced by removing any generated `.tags` files and relaunching.

**Atom Version**: 0.206.0
**System**: Mac OS X 10.10.3
**Thrown From**: [atom-ctags](https://github.com/yongkangchen/atom-ctags) package, v4.1.1

### Stack Trace

Uncaught TypeError: Cannot read property
'[path_to_file]' of undefined

```
At /Users/[user]/.atom/packages/atom-ctags/lib/ctags-cache.coffee:99

TypeError: Cannot read property '[path_to_file]' of undefined
  at /Users/[user]/.atom/packages/atom-ctags/lib/ctags-cache.coffee:99:26
  at /Users/[user]/.atom/packages/atom-ctags/lib/ctags-cache.coffee:92:7
  at exit (/Users/[user]/.atom/packages/atom-ctags/lib/tag-generator.coffee:62:5)
  at triggerExitCallback (/Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:213:47)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:227:18
  at Socket.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:98:18)
  at emitOne (events.js:82:20)
  at Socket.emit (events.js:166:7)
  at Pipe.close (net.js:464:12)

```

### Commands

```
     -2:13 core:select-all (atom-text-editor.editor.mini.is-focused)
     -2:12.7.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -1:52.1.0 core:close (div.settings-view.pane-item)
     -1:51.3.0 settings-view:open (atom-text-editor.editor.vim-mode.command-mode.is-focused)
     -1:42.9.0 core:select-all (atom-text-editor.editor.mini.is-focused)
     -1:42.5.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -1:39.1.0 core:select-all (atom-text-editor.editor.mini.is-focused)
     -1:38.9.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -1:12.1.0 pane:show-previous-item (atom-text-editor.editor.mini.is-focused)
     -1:11.4.0 atom-ctags:toggle-project-symbols (atom-text-editor.editor.vim-mode.command-mode.is-focused)
     -1:09.6.0 editor:consolidate-selections (atom-text-editor.editor.mini.is-focused)
     -1:09.6.0 core:cancel (atom-text-editor.editor.mini.is-focused)
     -1:08.7.0 atom-ctags:toggle-project-symbols (atom-text-editor.editor.vim-mode.command-mode.is-focused)
     -1:07.0 editor:consolidate-selections (atom-text-editor.editor.mini.is-focused)
     -1:07.0 core:cancel (atom-text-editor.editor.mini.is-focused)
     -0:01.0 atom-ctags:toggle-file-symbols (atom-text-editor.editor.vim-mode.command-mode.is-focused)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "whitespace",
      "linter-scss-lint",
      "symbols-view"
    ]
  }
}
```

### Installed Packages

```coffee
# User
atom-ctags, v4.1.1
color-picker, v2.0.4
linter, v0.12.6
linter-coffeelint, v0.3.1
linter-erb, v0.1.1
linter-jshint, v0.1.6
linter-ruby, v0.1.6
minimap, v4.9.4
vim-mode, v0.51.0

# Dev
No dev packages
```

**Comment by yongkangchen** [comment]
Thanks, your steps to reproduce the issue are very helpful. Release in v4.1.2, please try again.

**Comment by djpowers** [comment]
Just updated to the latest version and confirming that that fixed the issue. Thanks for the quick turnaround! :+1:
