### ISSUE TITLE
Failed to activate the atom-ctags package

### ISSUE THREAD

**Issue by fxlt** [yongkangchen/atom-ctags#109]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.0.0
**System**: Unknown Windows Version
**Thrown From**: [atom-ctags](https://github.com/yongkangchen/atom-ctags) package, v4.1.4

### Stack Trace

Failed to activate the atom-ctags package

```
At Module did not self-register.

Error: Module did not self-register.
  at Error (native)
  at Object.module.(anonymous function) (ATOM_SHELL_ASAR.js:118:20)
  at Object.module.(anonymous function) (ATOM_SHELL_ASAR.js:118:20)
  at Object.module.(anonymous function) [as .node] (ATOM_SHELL_ASAR.js:118:20)
  at Module.load (module.js:347:32)
  at Function.Module._load (module.js:302:12)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at Object.<anonymous> (C:\Users\Administrator\.atom\packages\atom-ctags\node_modules\ctags\src\ctags.coffee:1:10)
  at Object.<anonymous> (C:\Users\Administrator\.atom\packages\atom-ctags\node_modules\ctags\src\ctags.coffee:1:1)
  at Module._compile (module.js:452:26)
  at Object.requireCoffeeScript (C:\Users\Administrator\AppData\Local\atom\app-1.0.0\resources\app.asar\node_modules\coffee-cash\lib\coffee-cash.js:85:19)
  at Module.load (module.js:347:32)
  at Function.Module._load (module.js:302:12)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at Object.<anonymous> (C:\Users\Administrator\.atom\packages\atom-ctags\lib\ctags-cache.coffee:3:9)
  at Object.<anonymous> (C:\Users\Administrator\.atom\packages\atom-ctags\lib\ctags-cache.coffee:2:1)
  at Module._compile (module.js:452:26)
  at Object.requireCoffeeScript (C:\Users\Administrator\AppData\Local\atom\app-1.0.0\resources\app.asar\node_modules\coffee-cash\lib\coffee-cash.js:85:19)
  at Module.load (module.js:347:32)
  at Function.Module._load (module.js:302:12)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at Object.module.exports.activate (C:\Users\Administrator\.atom\packages\atom-ctags\lib\main.coffee:33:19)
  at Package.module.exports.Package.activateNow (C:\Users\Administrator\AppData\Local\atom\app-1.0.0\resources\app.asar\src\package.js:240:19)
  at C:\Users\Administrator\AppData\Local\atom\app-1.0.0\resources\app.asar\src\package.js:221:30
  at Package.module.exports.Package.measure (C:\Users\Administrator\AppData\Local\atom\app-1.0.0\resources\app.asar\src\package.js:165:15)
  at Package.module.exports.Package.activate (C:\Users\Administrator\AppData\Local\atom\app-1.0.0\resources\app.asar\src\package.js:213:14)
  at PackageManager.module.exports.PackageManager.activatePackage (C:\Users\Administrator\AppData\Local\atom\app-1.0.0\resources\app.asar\src\package-manager.js:452:21)
  at C:\Users\Administrator\AppData\Local\atom\app-1.0.0\resources\app.asar\node_modules\settings-view\lib\package-manager.js:362:29
  at exit (C:\Users\Administrator\AppData\Local\atom\app-1.0.0\resources\app.asar\node_modules\settings-view\lib\package-manager.js:53:16)
  at triggerExitCallback (C:\Users\Administrator\AppData\Local\atom\app-1.0.0\resources\app.asar\src\buffered-process.js:213:47)
  at ChildProcess.<anonymous> (C:\Users\Administrator\AppData\Local\atom\app-1.0.0\resources\app.asar\src\buffered-process.js:235:18)
  at emitTwo (events.js:87:13)
  at ChildProcess.emit (events.js:169:7)
  at Process.ChildProcess._handle.onexit (child_process.js:1057:12)

```

### Commands

```
     -8:42.5.0 command-palette:toggle (atom-text-editor.editor.is-focused)
 12x -8:38.7.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -8:12.6.0 editor:consolidate-selections (atom-text-editor.editor.mini.is-focused)
     -8:12.6.0 core:cancel (atom-text-editor.editor.mini.is-focused)
     -6:21.8.0 fuzzy-finder:toggle-file-finder (atom-text-editor.editor.is-focused)
  7x -6:16.7.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -6:14.1.0 editor:consolidate-selections (atom-text-editor.editor.mini.is-focused)
     -6:14.1.0 core:cancel (atom-text-editor.editor.mini.is-focused)
     -3:12.2.0 core:confirm (atom-text-editor.editor.mini.is-focused)
```

### Config

```json
{
  "core": {}
}
```

### Installed Packages

```coffee
# User
atom-ctags, v4.1.4
linter-php, v0.0.15

# Dev
No dev packages
```

**Comment by imalitavakoli** [comment]
Yes, I have the same issue. I think when the Atom Version 1.0.0 came out, this is happening...
A little update to fix this would be so much appreciated :)

Thanks.

**Comment by yongkangchen** [comment]
@Evrei @vstoykov @fxlt @imalitavakoli would you please try:
```
cd ~/.atom/package/atom-ctags
rm -rf node_modules/
apm install
```

**Comment by yongkangchen** [comment]
Also try:
```
cd ~/.atom/package/atom-ctags
apm rebuild
```

**Comment by brian-vogogo** [comment]
I am seeing this issue as well. 

1. Install atom-ctags -> see error mentioned above
2. Uninstall and re-install atom-ctags -> see error mentioned above
3. Restart Atom -> see warning that symbols-view is have been disabled
4. atom-ctags seems to work, can execute from command palette and keyboard shortcuts
5. Attempted combinations of reinstalling atom-ctags with and without symbols-view enabled -> unable to reproduce now

Atom: 1.0.0
atom-ctags: 4.1.4
symbols-view (0.99.0)
atom-beautify (0.28.7)
clipboard-history(0.6.6)
highlight-selected (0.10.1)
rails-transporter (1.2.0)
ruby-test (0.9.11)
last-cursor-position (0.9.0)
OSX Yosemite

**Comment by vstoykov** [comment]
@yongkangchen looks like it's working now

**Comment by jaitaiwan** [comment]
Just had this issue, it's still occuring.

**Comment by jhasse** [comment]
Me too

**Comment by vstoykov** [comment]
@jaitaiwan @jhasse did you guys removed the plugin completely and installing it again?

**Comment by jaitaiwan** [comment]
I did, also tried a fresh install of atom with just this plugin installed.
The OS itself is a clean install on a new computer as well so everything is
fairly stock standard

**Comment by seoker** [comment]
I had the same issue, just tried disabling the symbols-view and restart, it worked.

**Comment by vstoykov** [comment]
Probably now `atom-ctags` do not disable `symbols-view` on install.
@jaitaiwan @jhasse can you see if `symbols-view` plugin is enabled on your installations even after `atom-ctags` is installed?

**Comment by itkovian** [comment]
I can confirm it is still enabled after instilling atom-ctags.

**Comment by SalahAdDin** [comment]
I have that problem but i haven't `atom-ctags` installed.
