### ISSUE TITLE
Uncaught RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by JeanMertz** [yongkangchen/atom-ctags#110]
When hitting `cmd + shift + R`, I got the following error.

***

**Atom Version**: 1.0.0
**System**: Mac OS X 10.10.3
**Thrown From**: [atom-ctags](https://github.com/yongkangchen/atom-ctags) package, v4.1.4

### Stack Trace

Uncaught RangeError: Maximum call stack size exceeded

```
At /Users/Jean/.atom/packages/atom-ctags/lib/file-view.coffee:57

RangeError: Maximum call stack size exceeded
  at FileView.module.exports.FileView.toggleAll (/Users/Jean/.atom/packages/atom-ctags/lib/file-view.coffee:57:9)
  at atom-workspace.<anonymous> (/Users/Jean/.atom/packages/atom-ctags/lib/main.coffee:50:25)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/src/command-registry.js:241:29)
  at /opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:520:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:355:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:180:20)

```

### Commands

```
     -0:09.1.0 core:move-up (atom-text-editor.editor.is-focused)
  3x -0:08.8.0 editor:move-to-beginning-of-word (atom-text-editor.editor.is-focused)
     -0:07.6.0 editor:select-to-end-of-word (atom-text-editor.editor.is-focused)
     -0:07.5.0 editor:select-to-beginning-of-word (atom-text-editor.editor.is-focused)
     -0:07.3.0 editor:select-to-end-of-word (atom-text-editor.editor.is-focused)
     -0:07.2.0 editor:select-to-beginning-of-word (atom-text-editor.editor.is-focused)
     -0:07.1.0 editor:select-to-end-of-word (atom-text-editor.editor.is-focused)
     -0:07.0 editor:select-to-beginning-of-word (atom-text-editor.editor.is-focused)
     -0:06.9.0 editor:select-to-end-of-word (atom-text-editor.editor.is-focused)
     -0:06.8.0 editor:select-to-beginning-of-word (atom-text-editor.editor.is-focused)
     -0:06.7.0 editor:select-to-end-of-word (atom-text-editor.editor.is-focused)
     -0:06.6.0 editor:select-to-beginning-of-word (atom-text-editor.editor.is-focused)
     -0:06.5.0 editor:select-to-end-of-word (atom-text-editor.editor.is-focused)
     -0:01.4.0 core:copy (atom-text-editor.editor.is-focused)
     -0:01.0 atom-ctags:toggle-project-symbols (atom-text-editor.editor.is-focused)
     -0:00.5.0 core:paste (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "symbols-view"
    ]
  }
}
```

### Installed Packages

```coffee
# User
atom-ctags, v4.1.4
autocomplete-paths, v1.0.2
language-gherkin, v1.0.2
minimap, v4.10.0

# Dev
No dev packages
```

**Comment by dkarter** [comment]
I get the same error
