### ISSUE TITLE
Failed to activate the atom-ctags package

### ISSUE THREAD

**Issue by Evrei** [yongkangchen/atom-ctags#111]
1. ...
2. ...

**Atom Version**: 1.0.0
**System**: Mac OS X 10.10.3
**Thrown From**: [atom-ctags](https://github.com/yongkangchen/atom-ctags) package, v4.1.4

### Stack Trace

Failed to activate the atom-ctags package

```
At Module did not self-register.

Error: Module did not self-register.
  at Error (native)
  at Object.module.(anonymous function) (ATOM_SHELL_ASAR.js:118:20)
  at Object.module.(anonymous function) (ATOM_SHELL_ASAR.js:118:20)
  at Object.module.(anonymous function) [as .node] (ATOM_SHELL_ASAR.js:118:20)
  at Module.load (module.js:347:32)
  at Function.Module._load (module.js:302:12)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at Object.<anonymous> (/Users/evrei/.atom/packages/atom-ctags/node_modules/ctags/src/ctags.coffee:1:10)
  at Object.<anonymous> (/Users/evrei/.atom/packages/atom-ctags/node_modules/ctags/src/ctags.coffee:1:1)
  at Module._compile (module.js:452:26)
  at Object.requireCoffeeScript (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/coffee-cash/lib/coffee-cash.js:85:19)
  at Module.load (module.js:347:32)
  at Function.Module._load (module.js:302:12)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at Object.<anonymous> (/Users/evrei/.atom/packages/atom-ctags/lib/ctags-cache.coffee:3:9)
  at Object.<anonymous> (/Users/evrei/.atom/packages/atom-ctags/lib/ctags-cache.coffee:2:1)
  at Module._compile (module.js:452:26)
  at Object.requireCoffeeScript (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/coffee-cash/lib/coffee-cash.js:85:19)
  at Module.load (module.js:347:32)
  at Function.Module._load (module.js:302:12)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at Object.module.exports.activate (/Users/evrei/.atom/packages/atom-ctags/lib/main.coffee:33:19)
  at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:240:19)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:221:30
  at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:165:15)
  at Package.module.exports.Package.activate (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:213:14)
  at PackageManager.module.exports.PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:452:21)
  at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-manager.js:362:29
  at exit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-manager.js:53:16)
  at triggerExitCallback (/Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:213:47)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:227:18
  at Socket.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:98:18)
  at emitOne (events.js:82:20)
  at Socket.emit (events.js:166:7)
  at Pipe.close (net.js:464:12)

```

### Commands

```
     -2:06.0 core:paste (atom-text-editor.editor.mini.is-focused)
     -2:03.6.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -2:03.2.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:28.1.0 core:paste (atom-text-editor.editor.mini.is-focused)
     -0:27.8.0 core:confirm (atom-text-editor.editor.mini.is-focused)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "git-diff",
      "language-c",
      "language-clojure",
      "language-csharp",
      "language-gfm",
      "language-go",
      "language-java",
      "language-objective-c",
      "language-perl",
      "language-php",
      "language-python",
      "language-ruby",
      "language-ruby-on-rails",
      "language-sql",
      "language-toml",
      "language-yaml",
      "markdown-preview",
      "package-generator",
      "styleguide",
      "welcome",
      "timecop"
    ],
    "themes": [
      "isotope-ui",
      "monokai"
    ]
  }
}
```

### Installed Packages

```coffee
# User
atom-ctags, v4.1.4
isotope-ui, v2.4.2
monokai, v0.14.0
project-manager, v1.15.10
symbols-tree-view, v0.9.3

# Dev
No dev packages
```

**Comment by vstoykov** [comment]
I just tried to install it and have the same result. It says that the issue was already reported and when clicked opened this issue.

Atom Version: 1.0.0
System: Fedora 21
Thrown From: atom-ctags package, v4.1.4

The stack trace is the same

**Comment by yongkangchen** [comment]
Duplicate with #109
