### ISSUE TITLE
Uncaught TypeError: Arguments to path.join must be strings

### ISSUE THREAD

**Issue by udeth** [yongkangchen/atom-ctags#114]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.0.2
**System**: Microsoft Windows 8.1 企业版
**Thrown From**: [atom-ctags](https://github.com/yongkangchen/atom-ctags) package, v4.1.4

### Stack Trace

Uncaught TypeError: Arguments to path.join must be strings

```
At path.js:178

TypeError: Arguments to path.join must be strings
  at f (path.js:178:13)
  at Object.filter (native)
  at Object.win32.join (path.js:183:38)
  at module.exports (C:\Users\woqumai\.atom\packages\atom-ctags\lib\tag-generator.coffee:38:19)
  at Object.module.exports.generateTags (C:\Users\woqumai\.atom\packages\atom-ctags\lib\ctags-cache.coffee:86:5)
  at Object.module.exports.getOrCreateTags (C:\Users\woqumai\.atom\packages\atom-ctags\lib\ctags-cache.coffee:96:6)
  at FileView.module.exports.FileView.populate (C:\Users\woqumai\.atom\packages\atom-ctags\lib\file-view.coffee:101:17)
  at FileView.module.exports.FileView.toggle (C:\Users\woqumai\.atom\packages\atom-ctags\lib\file-view.coffee:41:8)
  at atom-text-editor.atom.commands.add.atom-ctags:toggle-file-symbols (C:\Users\woqumai\.atom\packages\atom-ctags\lib\main.coffee:53:62)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (C:\Users\woqumai\AppData\Local\atom\app-1.0.2\resources\app.asar\src\command-registry.js:241:29)
  at C:\Users\woqumai\AppData\Local\atom\app-1.0.2\resources\app.asar\src\command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (C:\Users\woqumai\AppData\Local\atom\app-1.0.2\resources\app.asar\node_modules\atom-keymap\lib\keymap-manager.js:520:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (C:\Users\woqumai\AppData\Local\atom\app-1.0.2\resources\app.asar\node_modules\atom-keymap\lib\keymap-manager.js:355:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (C:\Users\woqumai\AppData\Local\atom\app-1.0.2\resources\app.asar\src\window-event-handler.js:177:20)

```

### Commands

```
  2x -8:33 core:backspace (atom-text-editor.editor.is-focused)
     -8:29.2.0 autocomplete-plus:confirm (atom-text-editor.editor.is-focused.autocomplete-active)
     -8:29.2.0 snippets:expand (atom-text-editor.editor.is-focused.autocomplete-active)
 12x -8:22.4.0 core:backspace (atom-text-editor.editor.is-focused)
     -8:03.9.0 autocomplete-plus:confirm (atom-text-editor.editor.is-focused.autocomplete-active)
     -7:59.9.0 core:undo (atom-text-editor.editor.is-focused)
     -7:59.3.0 core:backspace (atom-text-editor.editor.is-focused)
 34x -7:27.5.0 symbols-tree-view:toggle (atom-text-editor.editor.is-focused)
     -6:12.1.0 core:paste (atom-text-editor.editor.mini.is-focused)
     -6:09.9.0 core:cut (atom-text-editor.editor.mini.is-focused)
     -4:19.3.0 tree-view:toggle (atom-text-editor.editor.is-focused)
     -3:25.2.0 core:paste (atom-text-editor.editor.mini.is-focused)
     -0:50.2.0 tree-view:toggle (div.settings-view.pane-item)
  5x -0:36.1.0 atom-ctags:toggle-file-symbols (atom-text-editor.editor.is-focused)
     -0:25.3.0 fuzzy-finder:toggle-file-finder (atom-text-editor.editor.is-focused)
  2x -0:03.9.0 atom-ctags:toggle-file-symbols (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "cht-menu",
      "keyboard-localization",
      "symbols-view"
    ]
  },
  "atom-ctags": {}
}
```

### Installed Packages

```coffee
# User
atom-ctags, v4.1.4
autocomplete-php, v0.3.6
docs-snippets, v0.8.0
linter-php, v1.0.2
minimap, v4.12.0
php-cs-fixer, v2.3.0
script, v2.26.3
symbols-tree-view, v0.9.3

# Dev
No dev packages
```

**Comment by yongkangchen** [comment]
I guess you did not open a project folder but a single file?

**Comment by yongkangchen** [comment]
Duplicate with #98
