### ISSUE TITLE
Uncaught TypeError: Cannot read property 'substring' of undefined

### ISSUE THREAD

**Issue by arover** [yongkangchen/atom-ctags#132]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.2.0
**System**: Mac OS X 10.11.1
**Thrown From**: [atom-ctags](https://github.com/yongkangchen/atom-ctags) package, v4.4.0

### Stack Trace

Uncaught TypeError: Cannot read property 'substring' of undefined

```
At /Users/arover/.atom/packages/atom-ctags/lib/ctags-provider.coffee:10

TypeError: Cannot read property 'substring' of undefined
    at tagToSuggestion (/Users/arover/.atom/packages/atom-ctags/lib/ctags-provider.coffee:10:27)
    at CtagsProvider.module.exports.CtagsProvider.getSuggestions (/Users/arover/.atom/packages/atom-ctags/lib/ctags-provider.coffee:40:26)
    at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/autocomplete-plus/lib/autocomplete-manager.js:286:56
    at Array.forEach (native)
    at AutocompleteManager.module.exports.AutocompleteManager.getSuggestionsFromProviders (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/autocomplete-plus/lib/autocomplete-manager.js:265:17)
    at AutocompleteManager.getSuggestionsFromProviders (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/autocomplete-plus/lib/autocomplete-manager.js:3:61)
    at AutocompleteManager.module.exports.AutocompleteManager.findSuggestions (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/autocomplete-plus/lib/autocomplete-manager.js:252:19)
    at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/autocomplete-plus/lib/autocomplete-manager.js:3:61
```

### Commands

```
     -1:05.6.0 autocomplete-plus:cancel (atom-text-editor.editor.is-focused.autocomplete-active)
     -1:04.6.0 core:save (atom-text-editor.editor.is-focused)
  2x -0:57.3.0 core:move-right (atom-text-editor.editor.is-focused)
     -0:56.1.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:55.2.0 core:move-right (atom-text-editor.editor.is-focused)
  3x -0:54.5.0 core:save (atom-text-editor.editor.is-focused)
     -0:06.4.0 core:move-down (atom-text-editor.editor.is-focused)
  2x -0:05.7.0 core:move-up (atom-text-editor.editor.is-focused)
     -0:04.8.0 editor:move-to-end-of-screen-line (atom-text-editor.editor.is-focused)
     -0:04.5.0 editor:newline (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "monokai"
    ],
    "disabledPackages": [
      "markdown-toc",
      "markdown-toc",
      "markdown-toc",
      "symbols-view"
    ]
  },
  "atom-ctags": {
    "cmdArgs": "--exclude=bower_components --exclude=node_modules"
  }
}
```

### Installed Packages

```coffee
# User
atom-ctags, v4.4.0
atom-jade, v0.3.0
autocomplete-ctags, v0.3.2
color-picker, v2.0.13
file-type-icons, v0.7.4
git-tab-status, v1.9.2
last-cursor-position, v0.9.0
linter, v1.11.1
minimap, v4.16.0
monokai, v0.18.0
space-tab, v0.4.2
symbols-tree-view, v0.10.1
webbox-color, v0.5.9

# Dev
No dev packages
```

**Comment by yongkangchen** [comment]
It seems that your tags parse error with a empty pattern. Still I fixed it by ignore the tag

**Comment by arover** [comment]
it happens when I'm writing angular1 js code. BTW , i like this atom package.
