### ISSUE TITLE
Path must be a string

### ISSUE THREAD

**Issue by loranger** [yongkangchen/atom-ctags#137]
Hello,

I have an issue using atom-ctags with atom-remote files.
Of course, they are not opened in a local project. but they are stored locally, in the same workspace.

**Atom Version**: 1.2.4
**System**: Mac OS X 10.11.1
**Thrown From**: [atom-ctags](https://github.com/yongkangchen/atom-ctags) package, v4.4.1
### Stack Trace

Uncaught TypeError: Path must be a string. Received undefined

```
At path.js:8

TypeError: Path must be a string. Received undefined
    at assertPath (path.js:8:11)
    at Object.posix.join (path.js:477:5)
    at module.exports (/Users/loranger/.atom/packages/atom-ctags/lib/tag-generator.coffee:38:19)
    at Object.module.exports.generateTags (/Users/loranger/.atom/packages/atom-ctags/lib/ctags-cache.coffee:87:5)
    at Object.module.exports.getOrCreateTags (/Users/loranger/.atom/packages/atom-ctags/lib/ctags-cache.coffee:97:6)
    at FileView.module.exports.FileView.populate (/Users/loranger/.atom/packages/atom-ctags/lib/file-view.coffee:101:17)
    at FileView.module.exports.FileView.toggle (/Users/loranger/.atom/packages/atom-ctags/lib/file-view.coffee:41:8)
    at atom-text-editor.atom.commands.add.atom-ctags:toggle-file-symbols (/Users/loranger/.atom/packages/atom-ctags/lib/main.coffee:65:62)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/opt/homebrew-cask/Caskroom/atom/1.2.4/Atom.app/Contents/Resources/app.asar/src/command-registry.js:260:29)
    at /opt/homebrew-cask/Caskroom/atom/1.2.4/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/opt/homebrew-cask/Caskroom/atom/1.2.4/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:533:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/opt/homebrew-cask/Caskroom/atom/1.2.4/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:356:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeydown (/opt/homebrew-cask/Caskroom/atom/1.2.4/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:99:36)
    at HTMLDocument.<anonymous> (/opt/homebrew-cask/Caskroom/atom/1.2.4/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:3:61)
```
### Commands

```
 34x -5:56 core:undo (atom-text-editor.editor.is-focused)
     -5:39.4.0 core:save (atom-text-editor.editor.is-focused)
     -5:03.6.0 core:move-up (atom-text-editor.editor.is-focused)
     -5:03.2.0 editor:move-to-end-of-screen-line (atom-text-editor.editor.is-focused)
     -5:00.7.0 autocomplete-plus:confirm (atom-text-editor.editor.is-focused.autocomplete-active)
     -5:00.7.0 snippets:expand (atom-text-editor.editor.is-focused.autocomplete-active)
     -5:00.1.0 core:move-left (atom-text-editor.editor.is-focused)
     -4:59.3.0 core:save (atom-text-editor.editor.is-focused)
     -4:42.5.0 editor:move-to-beginning-of-word (atom-text-editor.editor.is-focused)
  4x -4:42.2.0 core:move-left (atom-text-editor.editor.is-focused)
     -4:41.4.0 emmet:insert-formatted-line-break-only (atom-text-editor.editor.is-focused)
     -4:41.4.0 editor:newline (atom-text-editor.editor.is-focused)
     -4:40.8.0 core:save (atom-text-editor.editor.is-focused)
     -0:05.5.0 atom-ctags:toggle-file-symbols (atom-text-editor.editor.is-focused)
  3x -0:03.6.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:02.7.0 atom-ctags:toggle-file-symbols (atom-text-editor.editor.is-focused)
```
### Config

``` json
{
  "core": {
    "themes": [
      "nucleus-dark-ui",
      "gruvbox"
    ],
    "ignoredNames": [
      ".git",
      ".svn",
      ".DS_Store",
      ".sublime-project",
      ".sublime-workspace",
      "._"
    ],
    "packagesWithKeymapsDisabled": [
      "terminal-plus"
    ],
    "disabledPackages": [
      "terminal-plus",
      "symbols-view"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
Sublime-Style-Column-Selection, v1.3.0
aligner, v0.17.3
atom-beautify, v0.28.19
atom-ctags, v4.4.1
auto-detect-indentation, v0.4.2
autoclose-html, v0.19.0
build, v0.49.2
build-gulp, v0.4.0
editor-stats, v0.17.0
emmet, v2.3.15
file-icons, v1.6.13
gruvbox, v1.0.5
highlight-selected, v0.11.1
language-blade, v0.16.0
language-nginx, v0.6.1
laravel, v0.7.0
less-than-slash, v0.11.1
linter, v1.11.3
linter-csslint, v1.1.0
linter-htmlhint, v0.2.1
linter-jshint, v1.2.1
linter-jsonlint, v1.1.0
linter-php, v1.1.6
linter-sass-lint, v0.4.1
minimap, v4.16.2
minimap-find-and-replace, v4.3.2
minimap-highlight-selected, v4.3.1
minimap-pigments, v0.1.7
nucleus-dark-ui, v0.6.12
php-twig, v4.0.0
pigments, v0.19.1
remote-atom, v1.2.9

# Dev
No dev packages
```

**Comment by loranger** [comment]
Never mind
