### ISSUE TITLE
Failed to activate the atom-ctags package

### ISSUE THREAD

**Issue by clementschmitt** [yongkangchen/atom-ctags#154]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.5.4
**System**: Unknown Windows Version
**Thrown From**: [atom-ctags](https://github.com/yongkangchen/atom-ctags) package, v4.5.0

### Stack Trace

Failed to activate the atom-ctags package

```
At Module did not self-register.

Error: Module did not self-register.
    at Error (native)
    at Object.module.(anonymous function) (ATOM_SHELL_ASAR.js:137:20)
    at Object.module.(anonymous function) [as .node] (ATOM_SHELL_ASAR.js:137:20)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (C:\Users\asus\AppData\Local\atom\app-1.5.4\resources\app.asar\src\native-compile-cache.js:50:27)
    at Object.<anonymous> (file:///C:/Users/asus/.atom/packages/atom-ctags/node_modules/ctags/src/ctags.coffee:1:10)
    at Object.<anonymous> (file:///C:/Users/asus/.atom/packages/atom-ctags/node_modules/ctags/src/ctags.coffee:1:1)
    at Module._compile (C:\Users\asus\AppData\Local\atom\app-1.5.4\resources\app.asar\src\native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .coffee] (C:\Users\asus\AppData\Local\atom\app-1.5.4\resources\app.asar\src\compile-cache.js:208:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (C:\Users\asus\AppData\Local\atom\app-1.5.4\resources\app.asar\src\native-compile-cache.js:50:27)
    at Object.<anonymous> (file:///C:/Users/asus/.atom/packages/atom-ctags/lib/ctags-cache.coffee:3:9)
    at Object.<anonymous> (file:///C:/Users/asus/.atom/packages/atom-ctags/lib/ctags-cache.coffee:2:1)
    at Module._compile (C:\Users\asus\AppData\Local\atom\app-1.5.4\resources\app.asar\src\native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .coffee] (C:\Users\asus\AppData\Local\atom\app-1.5.4\resources\app.asar\src\compile-cache.js:208:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (C:\Users\asus\AppData\Local\atom\app-1.5.4\resources\app.asar\src\native-compile-cache.js:50:27)
    at Object.module.exports.activate (file:///C:/Users/asus/.atom/packages/atom-ctags/lib/main.coffee:48:19)
    at Package.module.exports.Package.activateNow (C:\Users\asus\AppData\Local\atom\app-1.5.4\resources\app.asar\src\package.js:181:20)
    at C:\Users\asus\AppData\Local\atom\app-1.5.4\resources\app.asar\src\package.js:155:32
    at Package.module.exports.Package.measure (C:\Users\asus\AppData\Local\atom\app-1.5.4\resources\app.asar\src\package.js:92:15)
    at C:\Users\asus\AppData\Local\atom\app-1.5.4\resources\app.asar\src\package.js:148:26
    at Package.module.exports.Package.activate (C:\Users\asus\AppData\Local\atom\app-1.5.4\resources\app.asar\src\package.js:145:34)
    at PackageManager.module.exports.PackageManager.activatePackage (C:\Users\asus\AppData\Local\atom\app-1.5.4\resources\app.asar\src\package-manager.js:526:21)
    at C:\Users\asus\AppData\Local\atom\app-1.5.4\resources\app.asar\node_modules\settings-view\lib\package-manager.js:444:29
    at exit (C:\Users\asus\AppData\Local\atom\app-1.5.4\resources\app.asar\node_modules\settings-view\lib\package-manager.js:73:16)
    at triggerExitCallback (C:\Users\asus\AppData\Local\atom\app-1.5.4\resources\app.asar\src\buffered-process.js:213:47)
    at ChildProcess.<anonymous> (C:\Users\asus\AppData\Local\atom\app-1.5.4\resources\app.asar\src\buffered-process.js:235:18)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
```

### Commands

```
  2x -9:34.7.0 editor:newline (atom-text-editor.editor.is-focused)
     -9:30 core:backspace (atom-text-editor.editor.is-focused)
     -9:25.2.0 autocomplete-plus:confirm (atom-text-editor.editor.is-focused.autocomplete-active)
     -9:22.2.0 autocomplete-plus:activate (atom-text-editor.editor.is-focused)
     -1:51.3.0 symbols-view:toggle-file-symbols (atom-text-editor.editor.is-focused)
 11x -1:47.5.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -1:25.6.0 symbols-view:toggle-project-symbols (atom-text-editor.editor.is-focused)
  5x -1:19.4.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -1:11.9.0 welcome:show (atom-text-editor.editor.is-focused)
     -0:51.3.0 core:confirm (atom-text-editor.editor.mini.is-focused)
```

### Config

```json
{
  "core": {
    "themes": [
      "one-dark-ui",
      "atom-dark-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
atom-ctags, v4.5.0
auto-indent, v0.5.0
color-picker, v2.1.1
editor-background, v1.2.17
last-cursor-position, v0.9.0

# Dev
No dev packages
```

**Comment by MathijsvVelde** [comment]
Same on Mac

1. install 'atom-ctags'
2. enable 'atom-ctags'

**Atom Version**: 1.5.4
**System**: Mac OS X 10.11.3
**Thrown From**: [atom-ctags](https://github.com/yongkangchen/atom-ctags) package, v4.5.0


### Stack Trace

Failed to activate the atom-ctags package

```
At Module did not self-register.

Error: Module did not self-register.
    at Error (native)
    at Object.module.(anonymous function) (ATOM_SHELL_ASAR.js:137:20)
    at Object.module.(anonymous function) (ATOM_SHELL_ASAR.js:137:20)
    at Object.module.(anonymous function) [as .node] (ATOM_SHELL_ASAR.js:137:20)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/Users/MeUser/.atom/packages/atom-ctags/node_modules/ctags/src/ctags.coffee:1:10)
    at Object.<anonymous> (/Users/MeUser/.atom/packages/atom-ctags/node_modules/ctags/src/ctags.coffee:1:1)
    at Module._compile (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .coffee] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/Users/MeUser/.atom/packages/atom-ctags/lib/ctags-cache.coffee:3:9)
    at Object.<anonymous> (/Users/MeUser/.atom/packages/atom-ctags/lib/ctags-cache.coffee:2:1)
    at Module._compile (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .coffee] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.module.exports.activate (/Users/MeUser/.atom/packages/atom-ctags/lib/main.coffee:48:19)
    at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:181:20)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:155:32
    at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:92:15)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:148:26
    at Package.module.exports.Package.activate (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:145:34)
    at PackageManager.module.exports.PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:526:21)
    at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-manager.js:444:29
    at exit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-manager.js:73:16)
    at triggerExitCallback (/Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:213:47)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:220:18
    at Socket.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:98:18)
    at emitOne (events.js:82:20)
    at Socket.emit (events.js:169:7)
    at Pipe._onclose (net.js:469:12)
```

### Commands

```
  2x -9:29.8.0 symbols-view:go-to-declaration (atom-text-editor.editor.is-focused)
     -9:22.2.0 settings-view:open (atom-text-editor.editor.is-focused)
  5x -9:14.9.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -8:45.7.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -6:10.9.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -5:34.6.0 symbols-view:toggle-file-symbols (atom-text-editor.editor.is-focused)
     -5:19.9.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -4:55.1.0 symbols-view:toggle-project-symbols (div.package-detail.panels-item)
  5x -4:46.1.0 core:backspace (atom-text-editor.editor.mini.is-focused)
  2x -3:43.6.0 core:confirm (atom-text-editor.editor.mini.is-focused)
  2x -1:23.7.0 core:backspace (atom-text-editor.editor.mini.is-focused)
  2x -1:21 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:27.1.0 core:paste (atom-text-editor.editor.mini.is-focused)
     -0:25.2.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -0:25 core:confirm (atom-text-editor.editor.mini.is-focused)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "coffee-navigator",
      "linter-coffeelint",
      "linter-jscs",
      "linter-phpcs",
      "linter-phpmd",
      "atom-watcher"
    ],
    "ignoredNames": [
      ".git",
      ".hg",
      ".svn",
      ".DS_Store",
      "._*",
      "Thumbs.db",
      "nbproject"
    ],
    "openEmptyEditorOnStart": false,
    "packagesWithKeymapsDisabled": [
      "coffee-compile"
    ],
    "projectHome": "/Users/MeUser/NetBeansProjects/",
    "themes": [
      "atom-material-ui",
      "atom-material-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
atom-beautify, v0.28.26
atom-ctags, v4.5.0
atom-material-syntax, v0.4.3
atom-material-ui, v1.2.1
atom-minify, v0.7.1
autocomplete-python, v1.7.0
bottom-dock, v0.3.7
build-make, v0.7.0
coffee-compile, v0.21.1
color-picker, v2.1.1
compare-files, v0.6.2
formatter, v2.12.3
git-utils, v4.1.2
grunt-manager, v0.1.15
intentions, v1.0.5
language-bridlensis, v1.0.1
language-nlf, v1.1.3
language-nsl, v1.5.1
language-nunjucks, v3.0.0
less-autocompile, v1.0.0
line-diff-details, v1.2.0
linter, v1.11.3
linter-coffeescript, v1.0.0
linter-csslint, v1.3.2
linter-htmlhint, v1.0.3
linter-jshint, v2.0.2
linter-jsonlint, v1.1.6
linter-markdown, v1.5.0
linter-php, v1.2.0
linter-sass-lint, v1.1.2
linter-scss-lint, v2.5.1
linter-xmllint, v1.3.4
minimap, v4.20.0
node-debugger, v1.4.4
nsis-plugins, v1.0.3
php-cs-fixer, v2.5.6
python-tools, v0.6.7

# Dev
No dev packages
```

**Comment by kasperientje** [comment]
Got the same error, here's my config:

[Enter steps to reproduce below:]

1. Install atom-ctags package
2. Enable atom-ctags package

**Atom Version**: 1.5.4
**System**: Mac OS X 10.11.3
**Thrown From**: [atom-ctags](https://github.com/yongkangchen/atom-ctags) package, v4.5.0


### Stack Trace

Failed to activate the atom-ctags package

```
At Module did not self-register.

Error: Module did not self-register.
    at Error (native)
    at Object.module.(anonymous function) (ATOM_SHELL_ASAR.js:137:20)
    at Object.module.(anonymous function) [as .node] (ATOM_SHELL_ASAR.js:137:20)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/Users/Kasper/.atom/packages/atom-ctags/node_modules/ctags/src/ctags.coffee:1:10)
    at Object.<anonymous> (/Users/Kasper/.atom/packages/atom-ctags/node_modules/ctags/src/ctags.coffee:1:1)
    at Module._compile (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .coffee] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/Users/Kasper/.atom/packages/atom-ctags/lib/ctags-cache.coffee:3:9)
    at Object.<anonymous> (/Users/Kasper/.atom/packages/atom-ctags/lib/ctags-cache.coffee:2:1)
    at Module._compile (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .coffee] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.module.exports.activate (/Users/Kasper/.atom/packages/atom-ctags/lib/main.coffee:48:19)
    at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:181:20)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:155:32
    at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:92:15)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:148:26
    at Package.module.exports.Package.activate (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:145:34)
    at PackageManager.module.exports.PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:526:21)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:338:19
    at /Applications/Atom.app/Contents/Resources/app.asar/src/config.js:631:20
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at Config.module.exports.Config.emitChangeEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/config.js:816:29)
    at Config.module.exports.Config.setRawValue (/Applications/Atom.app/Contents/Resources/app.asar/src/config.js:608:19)
    at Config.module.exports.Config.set (/Applications/Atom.app/Contents/Resources/app.asar/src/config.js:227:14)
    at Config.module.exports.Config.removeAtKeyPath (/Applications/Atom.app/Contents/Resources/app.asar/src/config.js:377:12)
    at Package.module.exports.Package.enable (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:77:26)
    at PackageManager.module.exports.PackageManager.enablePackage (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:165:14)
    at HTMLButtonElement.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-card.js:314:27)
    at HTMLButtonElement.jQuery.event.dispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/jquery/dist/jquery.js:4435:9)
    at HTMLButtonElement.elemData.handle (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/jquery/dist/jquery.js:4121:28)
```

### Commands

```
     -9:10 docblockr:parse-enter (atom-text-editor.editor.is-focused)
     -9:10 editor:newline (atom-text-editor.editor.is-focused)
     -9:08.8.0 autocomplete-plus:activate (atom-text-editor.editor.is-focused.autocomplete-active)
  5x -9:01.0 core:backspace (atom-text-editor.editor.is-focused.autocomplete-active)
     -8:50.6.0 autocomplete-plus:activate (atom-text-editor.editor.is-focused.autocomplete-active)
     -8:47.2.0 core:backspace (atom-text-editor.editor.is-focused.autocomplete-active)
  4x -8:46.7.0 autocomplete-plus:activate (atom-text-editor.editor.is-focused.autocomplete-active)
  6x -8:41.9.0 core:backspace (atom-text-editor.editor.is-focused.autocomplete-active)
     -3:17.3.0 settings-view:open (atom-text-editor.editor.is-focused)
  2x -3:14 core:backspace (atom-text-editor.editor.mini.is-focused)
  2x -3:12.5.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -1:09.0 application:new-file (a.btn-copy-report.icon.icon-clippy)
     -1:08.6.0 core:paste (atom-text-editor.editor.is-focused)
     -0:48.7.0 core:select-all (atom-text-editor.editor.is-focused)
     -0:48.2.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:04.0 settings-view:open (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "linter-clang",
      "linter"
    ],
    "themes": [
      "atom-dark-ui",
      "monokai"
    ]
  }
}
```

### Installed Packages

```coffee
# User
atom-ctags, v4.5.0
build, v0.55.0
docblockr, v0.7.3
language-glsl, v2.0.1
monokai, v0.18.0
terminal-panel, v1.14.1
you-complete-me, v0.7.1

# Dev
No dev packages
```

**Comment by uoryon** [comment]
+1

**Comment by yumao5** [comment]
+1

**Comment by josetapadas** [comment]
Same here.

[Enter steps to reproduce below:]

1. Install atom-ctags
2. Enable atom-ctags

**Atom Version**: 1.6.0
**System**: Mac OS X 10.11.3
**Thrown From**: [atom-ctags](https://github.com/yongkangchen/atom-ctags) package, v4.5.0


### Stack Trace

Failed to activate the atom-ctags package

```
At Module did not self-register.

Error: Module did not self-register.
    at Error (native)
    at Object.module.(anonymous function) (ATOM_SHELL_ASAR.js:137:20)
    at Object.module.(anonymous function) (ATOM_SHELL_ASAR.js:137:20)
    at Object.module.(anonymous function) [as .node] (ATOM_SHELL_ASAR.js:137:20)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/Users/josealves/.atom/packages/atom-ctags/node_modules/ctags/src/ctags.coffee:1:10)
    at Object.<anonymous> (/Users/josealves/.atom/packages/atom-ctags/node_modules/ctags/src/ctags.coffee:1:1)
    at Module._compile (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .coffee] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/Users/josealves/.atom/packages/atom-ctags/lib/ctags-cache.coffee:3:9)
    at Object.<anonymous> (/Users/josealves/.atom/packages/atom-ctags/lib/ctags-cache.coffee:2:1)
    at Module._compile (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .coffee] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.module.exports.activate (/Users/josealves/.atom/packages/atom-ctags/lib/main.coffee:48:19)
    at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:181:20)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:155:32
    at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:92:15)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:148:26
    at Package.module.exports.Package.activate (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:145:34)
    at PackageManager.module.exports.PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:526:21)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:338:19
    at /Applications/Atom.app/Contents/Resources/app.asar/src/config.js:631:20
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at Config.module.exports.Config.emitChangeEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/config.js:816:29)
    at Config.module.exports.Config.setRawValue (/Applications/Atom.app/Contents/Resources/app.asar/src/config.js:608:19)
    at Config.module.exports.Config.set (/Applications/Atom.app/Contents/Resources/app.asar/src/config.js:227:14)
    at Config.module.exports.Config.removeAtKeyPath (/Applications/Atom.app/Contents/Resources/app.asar/src/config.js:377:12)
    at Package.module.exports.Package.enable (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:77:26)
    at PackageManager.module.exports.PackageManager.enablePackage (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:165:14)
    at HTMLButtonElement.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-card.js:314:27)
    at HTMLButtonElement.jQuery.event.dispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/jquery/dist/jquery.js:4435:9)
    at HTMLButtonElement.elemData.handle (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/jquery/dist/jquery.js:4121:28)
```

### Commands

```
     -0:56.5.0 pane:show-item-1 (atom-text-editor.editor.is-focused)
     -0:56.1.0 pane:show-item-2 (atom-text-editor.editor.is-focused)
     -0:55.7.0 pane:show-item-1 (atom-text-editor.editor.is-focused)
     -0:55.3.0 pane:show-item-2 (atom-text-editor.editor.is-focused)
     -0:54.9.0 pane:show-item-1 (atom-text-editor.editor.is-focused)
     -0:54.6.0 pane:show-item-2 (atom-text-editor.editor.is-focused)
     -0:54.2.0 pane:show-item-1 (atom-text-editor.editor.is-focused)
     -0:53.9.0 pane:show-item-2 (atom-text-editor.editor.is-focused)
     -0:53.5.0 pane:show-item-1 (atom-text-editor.editor.is-focused)
     -0:53.2.0 pane:show-item-2 (atom-text-editor.editor.is-focused)
     -0:52.7.0 pane:show-item-1 (atom-text-editor.editor.is-focused)
     -0:52 pane:show-item-2 (atom-text-editor.editor.is-focused)
     -0:50.4.0 core:move-down (atom-text-editor.editor.is-focused)
     -0:35.6.0 symbols-view:go-to-declaration (atom-text-editor.editor.is-focused)
     -0:26.5.0 editor:select-to-first-character-of-line (atom-text-editor.editor.mini.is-focused)
     -0:25.7.0 core:confirm (atom-text-editor.editor.mini.is-focused)
```

### Config

```json
{
  "core": {
    "themes": [
      "spacegray-eighties-ui",
      "twilight-syntax-spacegray-eighties"
    ]
  },
  "atom-ctags": {}
}
```

### Installed Packages

```coffee
# User
atom-ctags, v4.5.0
autocomplete-ctags, v0.4.0
autocomplete-ruby, v0.1.0
file-icons, v1.6.18
linter, v1.11.3
linter-reek, v2.1.5
linter-rubocop, v0.4.7
linter-ruby, v1.2.2
pretty-json, v0.4.1
rest-client, v1.0.0
spacegray-eighties-ui, v1.2.0
twilight-syntax-spacegray-eighties, v0.3.0

# Dev
No dev packages
```

**Comment by mmqun** [comment]
+1 win7

**Comment by seekwe** [comment]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.7.0-beta0
**System**:  Windows 8
**Thrown From**: [atom-ctags](https://github.com/yongkangchen/atom-ctags) package, v4.5.0


### Stack Trace

Failed to activate the atom-ctags package

```
At Module did not self-register.

Error: Module did not self-register.
    at Error (native)
    at process.module.(anonymous function) (ATOM_SHELL_ASAR.js:159:20)
    at process.module.(anonymous function) [as dlopen] (ATOM_SHELL_ASAR.js:159:20)
    at Object.Module._extensions..node (module.js:450:18)
    at Object.module.(anonymous function) (ATOM_SHELL_ASAR.js:159:20)
    at Object.module.(anonymous function) [as .node] (ATOM_SHELL_ASAR.js:159:20)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (D:\seekwe\Atom Beta\resources\app.asar\src\native-compile-cache.js:50:27)
    at Object.<anonymous> (file:///D:/seekwe/.atom/packages/atom-ctags/node_modules/ctags/src/ctags.coffee:1:10)
    at Object.<anonymous> (file:///D:/seekwe/.atom/packages/atom-ctags/node_modules/ctags/src/ctags.coffee:1:1)
    at Module._compile (D:\seekwe\Atom Beta\resources\app.asar\src\native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .coffee] (D:\seekwe\Atom Beta\resources\app.asar\src\compile-cache.js:208:21)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (D:\seekwe\Atom Beta\resources\app.asar\src\native-compile-cache.js:50:27)
    at Object.<anonymous> (file:///D:/seekwe/.atom/packages/atom-ctags/lib/ctags-cache.coffee:3:9)
    at Object.<anonymous> (file:///D:/seekwe/.atom/packages/atom-ctags/lib/ctags-cache.coffee:2:1)
    at Module._compile (D:\seekwe\Atom Beta\resources\app.asar\src\native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .coffee] (D:\seekwe\Atom Beta\resources\app.asar\src\compile-cache.js:208:21)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (D:\seekwe\Atom Beta\resources\app.asar\src\native-compile-cache.js:50:27)
    at Object.module.exports.activate (file:///D:/seekwe/.atom/packages/atom-ctags/lib/main.coffee:48:19)
    at Package.module.exports.Package.activateNow (D:\seekwe\Atom Beta\resources\app.asar\src\package.js:183:20)
    at D:\seekwe\Atom Beta\resources\app.asar\src\package.js:156:32
    at Package.module.exports.Package.measure (D:\seekwe\Atom Beta\resources\app.asar\src\package.js:92:15)
    at D:\seekwe\Atom Beta\resources\app.asar\src\package.js:149:26
    at Package.module.exports.Package.activate (D:\seekwe\Atom Beta\resources\app.asar\src\package.js:146:34)
    at PackageManager.module.exports.PackageManager.activatePackage (D:\seekwe\Atom Beta\resources\app.asar\src\package-manager.js:535:21)
    at D:\seekwe\Atom Beta\resources\app.asar\node_modules\settings-view\lib\package-manager.js:448:29
    at exit (D:\seekwe\Atom Beta\resources\app.asar\node_modules\settings-view\lib\package-manager.js:73:16)
    at triggerExitCallback (D:\seekwe\Atom Beta\resources\app.asar\src\buffered-process.js:215:47)
    at ChildProcess.<anonymous> (D:\seekwe\Atom Beta\resources\app.asar\src\buffered-process.js:237:18)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
```

### Commands

```
     -6:28.7.0 snippets:expand (atom-text-editor.editor.is-focused.autocomplete-active)
  2x -6:27.8.0 editor:newline (atom-text-editor.editor.is-focused)
     -6:26.7.0 core:move-up (atom-text-editor.editor.is-focused)
 14x -6:22.9.0 core:backspace (atom-text-editor.editor.is-focused)
     -4:36.9.0 editor:move-to-next-subword-boundary (atom-text-editor.editor.is-focused)
     -4:32.8.0 core:backspace (atom-text-editor.editor.is-focused)
     -4:10.6.0 symbols-view:go-to-declaration (atom-text-editor.editor.is-focused)
     -4:07.1.0 tree-view:reveal-active-file (atom-text-editor.editor.is-focused)
  2x -4:01.4.0 symbols-view:go-to-declaration (atom-text-editor.editor.is-focused)
     -3:18.1.0 editor:newline (atom-text-editor.editor.is-focused)
  3x -3:16.5.0 core:backspace (atom-text-editor.editor.is-focused)
  2x -2:27.7.0 symbols-view:toggle-file-symbols (atom-text-editor.editor.is-focused)
     -2:16.8.0 core:backspace (atom-text-editor.editor.is-focused)
     -2:15.4.0 core:undo (atom-text-editor.editor.is-focused)
     -1:18.4.0 core:paste (atom-text-editor.editor.mini.is-focused)
     -1:17.7.0 core:confirm (atom-text-editor.editor.mini.is-focused)
```

### Config

```json
{
  "core": {
    "autoHideMenuBar": true
  }
}
```

### Installed Packages

```coffee
# User
atom-ctags, v4.5.0
autocomplete-php, v0.3.7
linter, v1.11.3
linter-php, v1.2.0
simplified-chinese-menu, v3.4.11

# Dev
No dev packages
```

**Comment by yongkangchen** [comment]
Hi，according to http://lexsheehan.blogspot.com/2015/03/simple-fix-for-module-did-not-self.html
you can try uninstall atom-ctags and reinstall atom-ctags

**Comment by Greenek** [comment]
To fix the problem:

1. disable `symbol-view` package
2. try to uninstall `atom-ctags`
  - if it fails or package is still visible as installed - restart Atom and package should disappear
3. install `atom-ctags` back again
