### ISSUE TITLE
Uncaught ReferenceError: Tags is not defined

### ISSUE THREAD

**Issue by zongUMR** [yongkangchen/atom-ctags#162]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.7.2
**System**: Mac OS X 10.11.4
**Thrown From**: [atom-ctags](https://github.com/yongkangchen/atom-ctags) package, v4.5.2

### Stack Trace

Uncaught ReferenceError: Tags is not defined

```
At /Users/zongm/.atom/packages/atom-ctags/node_modules/ctags/src/ctags.coffee:31

ReferenceError: Tags is not defined
    at Object.exports.createReadStream (/Users/zongm/.atom/packages/atom-ctags/node_modules/ctags/src/ctags.coffee:31:21)
    at Object.module.exports.readTags (/Users/zongm/.atom/packages/atom-ctags/lib/ctags-cache.coffee:41:20)
    at /Users/zongm/.atom/packages/atom-ctags/lib/ctags-cache.coffee:91:8
    at exit (/Users/zongm/.atom/packages/atom-ctags/lib/tag-generator.coffee:66:5)
    at triggerExitCallback (/Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:215:47)
    at ChildProcess.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:237:18)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
```

### Commands

```
     -0:29.7.0 application:open (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
     -0:01.1.0 atom-ctags:rebuild (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "symbols-view"
    ]
  }
}
```

### Installed Packages

```coffee
# User
atom-ctags, v4.5.2
autocomplete-go, v1.0.6
builder-go, v1.0.0
go-config, v1.1.4
go-get, v1.0.3
go-plus, v4.1.0
gofmt, v1.1.6
gometalinter-linter, v1.1.0
gorename, v1.0.2
linter, v1.11.4
navigator-godef, v1.0.3
react, v0.15.0
react-snippets, v0.4.2
tester-go, v1.0.4
vim-mode, v0.65.0

# Dev
No dev packages
```

**Comment by yongkangchen** [comment]
Please check if this file exist: 
```shell
/Applications/Atom.app/Contents/Resources/app.asar.unpacked/node_modules/symbols-view/node_modules/ctags/build/Release/ctags.node
```
