### ISSUE TITLE
I cant use it and I dont know why 

### ISSUE THREAD

**Issue by rainbowyu** [yongkangchen/atom-ctags#171]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.8.0
**System**: Unknown Windows Version
**Thrown From**: [atom-ctags](https://github.com/yongkangchen/atom-ctags) package, v4.5.2

### Stack Trace

Failed to activate the atom-ctags package

```
At Module did not self-register.

Error: Module did not self-register.
    at Error (native)
    at process.module.(anonymous function) (ATOM_SHELL_ASAR.js:159:20)
    at process.module.(anonymous function) (ATOM_SHELL_ASAR.js:159:20)
    at process.module.(anonymous function) [as dlopen] (ATOM_SHELL_ASAR.js:159:20)
    at Object.Module._extensions..node (module.js:450:18)
    at Object.module.(anonymous function) (ATOM_SHELL_ASAR.js:159:20)
    at Object.module.(anonymous function) (ATOM_SHELL_ASAR.js:159:20)
    at Object.module.(anonymous function) [as .node] (ATOM_SHELL_ASAR.js:159:20)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (C:\Users\genuinetek\AppData\Local\atom\app-1.8.0\resources\app.asar\src\native-compile-cache.js:50:27)
    at Object.<anonymous> (file:///C:/Users/genuinetek/.atom/packages/atom-ctags/node_modules/ctags/src/ctags.coffee:1:10)
    at Object.<anonymous> (file:///C:/Users/genuinetek/.atom/packages/atom-ctags/node_modules/ctags/src/ctags.coffee:1:1)
    at Module._compile (C:\Users\genuinetek\AppData\Local\atom\app-1.8.0\resources\app.asar\src\native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .coffee] (C:\Users\genuinetek\AppData\Local\atom\app-1.8.0\resources\app.asar\src\compile-cache.js:208:21)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (C:\Users\genuinetek\AppData\Local\atom\app-1.8.0\resources\app.asar\src\native-compile-cache.js:50:27)
    at Object.<anonymous> (file:///C:/Users/genuinetek/.atom/packages/atom-ctags/lib/ctags-cache.coffee:3:9)
    at Object.<anonymous> (file:///C:/Users/genuinetek/.atom/packages/atom-ctags/lib/ctags-cache.coffee:2:1)
    at Module._compile (C:\Users\genuinetek\AppData\Local\atom\app-1.8.0\resources\app.asar\src\native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .coffee] (C:\Users\genuinetek\AppData\Local\atom\app-1.8.0\resources\app.asar\src\compile-cache.js:208:21)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (C:\Users\genuinetek\AppData\Local\atom\app-1.8.0\resources\app.asar\src\native-compile-cache.js:50:27)
    at Object.module.exports.activate (file:///C:/Users/genuinetek/.atom/packages/atom-ctags/lib/main.coffee:48:19)
    at Package.module.exports.Package.activateNow (C:\Users\genuinetek\AppData\Local\atom\app-1.8.0\resources\app.asar\src\package.js:183:20)
    at C:\Users\genuinetek\AppData\Local\atom\app-1.8.0\resources\app.asar\src\package.js:156:32
    at Package.module.exports.Package.measure (C:\Users\genuinetek\AppData\Local\atom\app-1.8.0\resources\app.asar\src\package.js:92:15)
    at C:\Users\genuinetek\AppData\Local\atom\app-1.8.0\resources\app.asar\src\package.js:149:26
    at Package.module.exports.Package.activate (C:\Users\genuinetek\AppData\Local\atom\app-1.8.0\resources\app.asar\src\package.js:146:34)
    at PackageManager.module.exports.PackageManager.activatePackage (C:\Users\genuinetek\AppData\Local\atom\app-1.8.0\resources\app.asar\src\package-manager.js:538:21)
    at C:\Users\genuinetek\AppData\Local\atom\app-1.8.0\resources\app.asar\node_modules\settings-view\lib\package-manager.js:452:29
    at exit (C:\Users\genuinetek\AppData\Local\atom\app-1.8.0\resources\app.asar\node_modules\settings-view\lib\package-manager.js:73:16)
    at triggerExitCallback (C:\Users\genuinetek\AppData\Local\atom\app-1.8.0\resources\app.asar\src\buffered-process.js:215:47)
    at ChildProcess.<anonymous> (C:\Users\genuinetek\AppData\Local\atom\app-1.8.0\resources\app.asar\src\buffered-process.js:237:18)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
```

### Commands

```
     -9:28 encoding-selector:show (atom-text-editor.editor.is-focused)
  5x -9:23.6.0 symbols-view:go-to-declaration (atom-text-editor.editor.is-focused)
 23x -8:48.1.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -8:12.4.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -7:00.8.0 symbols-view:go-to-declaration (atom-text-editor.editor.is-focused)
     -6:54.7.0 tree-view:reveal-active-file (atom-text-editor.editor.is-focused)
     -6:38.2.0 encoding-selector:show (atom-text-editor.editor.is-focused)
     -4:35.9.0 application:open-your-keymap (atom-workspace.workspace.scrollbars-visible-always.theme-base16-tomorrow-dark-theme.theme-atom-dark-ui)
     -4:09.1.0 core:paste (atom-text-editor.editor.is-focused)
  7x -3:49.9.0 core:backspace (atom-text-editor.editor.power-mode.is-focused)
     -3:47.6.0 editor:newline (atom-text-editor.editor.power-mode.is-focused)
     -3:38 core:backspace (atom-text-editor.editor.power-mode.is-focused)
  2x -2:27.2.0 core:save (atom-text-editor.editor.power-mode.is-focused)
  8x -2:11.8.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -2:05.0 core:confirm (atom-text-editor.editor.mini.is-focused)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "activate-power-mode"
    ],
    "themes": [
      "atom-dark-ui",
      "base16-tomorrow-dark-theme"
    ]
  }
}
```

### Installed Packages

```coffee
# User
atom-ctags, v4.5.2

# Dev
No dev packages
```

**Comment by Semigradsky** [comment]
Run Atom as administrator. I have had the same issue.
