### ISSUE TITLE
At Cannot find module 'D:\Tools\Atom\resources/app/node_modules/ctags/build/Release/ctags.node'

### ISSUE THREAD

**Issue by WeighSong** [yongkangchen/atom-ctags#189]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.16.0 ia32
**Electron**: 1.3.13
**OS**: Unknown Windows version
**Thrown From**: [atom-ctags](https://github.com/yongkangchen/atom-ctags) package 5.1.0

### Stack Trace

Failed to activate the atom-ctags package

```
At Cannot find module 'D:\Tools\Atom\resources/app/node_modules/ctags/build/Release/ctags.node'

Error: Cannot find module 'D:\Tools\Atom\resources/app/node_modules/ctags/build/Release/ctags.node'
    at Module._resolveFilename (module.js:455:15)
    at Module._resolveFilename (D:/Tools/Atom/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._resolveFilename (/app.asar/src/module-cache.js:383:52)
    at Function.Module._load (module.js:403:25)
    at Module.require (module.js:483:17)
    at require (/app.asar/src/native-compile-cache.js:50:27)
    at /packages/atom-ctags/node_modules/ctags/src/ctags.coffee:1:10)
    at /packages/atom-ctags/node_modules/ctags/src/ctags.coffee:1:1)
    at Module._compile (/app.asar/src/native-compile-cache.js:109:30)
    at /app.asar/src/compile-cache.js:216:21)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (/app.asar/src/native-compile-cache.js:50:27)
    at /packages/atom-ctags/lib/ctags-cache.coffee:3:9)
    at /packages/atom-ctags/lib/ctags-cache.coffee:2:1)
    at Module._compile (/app.asar/src/native-compile-cache.js:109:30)
    at /app.asar/src/compile-cache.js:216:21)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (/app.asar/src/native-compile-cache.js:50:27)
    at Object.activate (/packages/atom-ctags/lib/main.coffee:48:19)
    at Package.module.exports.Package.activateNow (/app.asar/src/package.js:218:19)
    at /app.asar/src/package.js:190:32
    at Package.module.exports.Package.measure (/app.asar/src/package.js:96:15)
    at /app.asar/src/package.js:183:26
    at Package.module.exports.Package.activate (/app.asar/src/package.js:180:34)
    at PackageManager.module.exports.PackageManager.activatePackage (/app.asar/src/package-manager.js:550:34)
    at /app.asar/src/package-manager.js:352:19
    at /app.asar/src/config.js:635:20
    at Function.module.exports.Emitter.simpleDispatch (/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/app.asar/node_modules/event-kit/lib/emitter.js:141:28)
    at Config.module.exports.Config.emitChangeEvent (/app.asar/src/config.js:826:29)
    at Config.module.exports.Config.setRawValue (/app.asar/src/config.js:612:19)
    at Config.module.exports.Config.set (/app.asar/src/config.js:227:14)
    at Config.module.exports.Config.removeAtKeyPath (/app.asar/src/config.js:377:12)
    at Package.module.exports.Package.enable (/app.asar/src/package.js:81:26)
    at PackageManager.module.exports.PackageManager.enablePackage (/app.asar/src/package-manager.js:173:14)
    at HTMLButtonElement.enablementButtonClickHandler (/app.asar/node_modules/settings-view/lib/package-card.js:353:25)
```

### Commands

```
```

### Non-Core Packages

```
aligner 1.2.0 
aligner-javascript 1.1.0 
atom-ctags 5.1.0 
atom-material-ui 1.3.10 
docblockr 0.10.3 
ex-mode 0.14.0 
file-header 1.13.4 
git-plus 7.8.0 
gruvbox-plus-syntax 1.3.1 
highlight-column 0.5.2 
highlight-line 0.12.0 
highlight-selected 0.13.1 
line-diff-details 1.8.0 
minimap 4.28.2 
platformio-ide-terminal 2.5.1 
relative-numbers 0.8.0 
sublime-block-comment 0.5.1 
Sublime-Style-Column-Selection 1.7.4 
symbols-tree-view 0.14.0 
tree-view-git-status 1.4.0 
vim-mode 0.66.0 
vim-mode-plus 0.92.1 
vim-mode-plus-ex-mode 0.9.0 
```

**Comment by xingtaowap** [comment]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.16.0 x64
**Electron**: 1.3.13
**OS**: Unknown Windows version
**Thrown From**: [atom-ctags](https://github.com/yongkangchen/atom-ctags) package 5.1.0


### Stack Trace

Failed to activate the atom-ctags package

```
At %1 is not a valid Win32 application.
\\?\E:\workSoft\Atom x64\resources\app.asar.unpacked\node_modules\symbols-view\node_modules\ctags\build\Release\ctags.node

Error: %1 is not a valid Win32 application.
\\?\E:\workSoft\Atom x64\resources\app.asar.unpacked\node_modules\symbols-view\node_modules\ctags\build\Release\ctags.node
    at Error (native)
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:168:20)
    at Object.Module._extensions..node (module.js:583:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:168:20)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (/app.asar/src/native-compile-cache.js:50:27)
    at /packages/atom-ctags/node_modules/ctags/src/ctags.coffee:1:10)
    at /packages/atom-ctags/node_modules/ctags/src/ctags.coffee:1:1)
    at Module._compile (/app.asar/src/native-compile-cache.js:109:30)
    at /app.asar/src/compile-cache.js:216:21)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (/app.asar/src/native-compile-cache.js:50:27)
    at /packages/atom-ctags/lib/ctags-cache.coffee:3:9)
    at /packages/atom-ctags/lib/ctags-cache.coffee:2:1)
    at Module._compile (/app.asar/src/native-compile-cache.js:109:30)
    at /app.asar/src/compile-cache.js:216:21)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (/app.asar/src/native-compile-cache.js:50:27)
    at Object.activate (/packages/atom-ctags/lib/main.coffee:48:19)
    at Package.module.exports.Package.activateNow (/app.asar/src/package.js:218:19)
    at /app.asar/src/package.js:190:32
```

### Commands

```
```

### Non-Core Packages

```
activate-power-mode 1.4.0 
aligner-scss 1.1.0 
an-color-picker 1.0.2 
angular-2-typeScript-snippets 0.6.3 
atom-beautify 0.29.23 
atom-ctags 5.1.0 
atom-html-preview 0.1.22 
atom-jade 0.3.0 
atom-keyboard-macros 0.9.2 
atom-minify 0.8.0 
atom-terminal-panel 4.4.4 
atom-ternjs 0.18.3 
atomic-chrome 0.3.0 
autocomplete-js-import 1.4.0 
autocomplete-jsp 1.2.0 
autocomplete-modules 1.6.9 
autocomplete-paths 1.0.5 
block-comment-plus 0.4.0 
browser-plus 0.0.87 
busy-signal 1.4.1 
compass 0.9.1 
emmet 2.4.3 
expand-region 0.2.7 
file-type-icons 1.3.3 
go-plus 5.5.0 
goto-definition 1.3.3 
highlight-selected 0.13.1 
hyperclick 0.0.40 
intentions 1.1.2 
js-hyperclick 1.11.0 
language-vue 0.21.2 
language-vue-component 0.5.0 
linter 2.1.4 
linter-eslint 8.1.7 
linter-ui-default 1.2.4 
livestyle-atom 0.2.9 
minimap 4.28.2 
minimap-highlight-selected 4.6.1 
multi-cursor 2.1.5 
open-in-browser 0.5.0 
pigments 0.39.1 
platformio-ide-terminal 2.5.0 
preview-plus 1.2.7 
project-manager 3.3.4 
react 0.16.2 
sass-autocompile 0.13.3 
script 3.14.1 
simplified-chinese-menu 5.3.1 
sync-settings 0.8.1 
tortoise-svn 0.5.0 
wxapp 0.1.0 
```
