### ISSUE TITLE
Failed to activate the atom-ctags package

### ISSUE THREAD

**Issue by smokesea** [yongkangchen/atom-ctags#192]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.16.0 x64
**Electron**: 1.3.13
**OS**: Mac OS X 10.12.5
**Thrown From**: [atom-ctags](https://github.com/yongkangchen/atom-ctags) package 5.1.0

### Stack Trace

Failed to activate the atom-ctags package

```
At Cannot find module '/Applications/Atom.app/Contents/Resources/app/node_modules/ctags/build/Release/ctags.node'

Error: Cannot find module '/Applications/Atom.app/Contents/Resources/app/node_modules/ctags/build/Release/ctags.node'
    at Module._resolveFilename (module.js:455:15)
    at Module._resolveFilename (/Applications/Atom.app/Contents/Resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._resolveFilename (/app.asar/src/module-cache.js:383:52)
    at Function.Module._load (module.js:403:25)
    at Module.require (module.js:483:17)
    at require (/app.asar/src/native-compile-cache.js:50:27)
    at /packages/atom-ctags/node_modules/ctags/src/ctags.coffee:1:10)
    at /packages/atom-ctags/node_modules/ctags/src/ctags.coffee:1:1)
    at Module._compile (/app.asar/src/native-compile-cache.js:109:30)
    at /app.asar/src/compile-cache.js:216:21)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (/app.asar/src/native-compile-cache.js:50:27)
    at /packages/atom-ctags/lib/ctags-cache.coffee:3:9)
    at /packages/atom-ctags/lib/ctags-cache.coffee:2:1)
    at Module._compile (/app.asar/src/native-compile-cache.js:109:30)
    at /app.asar/src/compile-cache.js:216:21)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (/app.asar/src/native-compile-cache.js:50:27)
    at Object.activate (/packages/atom-ctags/lib/main.coffee:48:19)
    at Package.module.exports.Package.activateNow (/app.asar/src/package.js:218:19)
    at /app.asar/src/package.js:190:32
    at Package.module.exports.Package.measure (/app.asar/src/package.js:96:15)
    at /app.asar/src/package.js:183:26
    at Package.module.exports.Package.activate (/app.asar/src/package.js:180:34)
    at PackageManager.module.exports.PackageManager.activatePackage (/app.asar/src/package-manager.js:550:34)
    at /app.asar/node_modules/settings-view/lib/package-manager.js:484:29
    at exit (/app.asar/node_modules/settings-view/lib/package-manager.js:99:16)
    at triggerExitCallback (/app.asar/src/buffered-process.js:322:11)
    at /app.asar/src/buffered-process.js:335:11
    at /app.asar/src/buffered-process.js:204:9)
    at emitOne (events.js:101:20)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:493:12)
```

### Commands

```
  4x -1:04.1.0 core:backspace (input.hidden-input)
     -1:00.1.0 core:confirm (input.hidden-input)
     -0:06.1.0 core:copy (atom-notification.fatal.icon.icon-bug.native-key-bindings.has-detail.has-close.has-stack)
```

### Non-Core Packages

```
atom-ctags 5.1.0 
atom-runner 2.7.1 
atom-ternjs 0.18.3 
busy-signal 1.4.3 
go-debug 1.3.2 
go-plus 5.5.5 
go-signature-statusbar 1.2.0 
godef 0.2.5 
hyperclick 0.1.2 
intentions 1.1.2 
linter 2.2.0 
linter-eslint 8.2.1 
linter-ui-default 1.2.4 
```

**Comment by ioquatix** [comment]
I'm having almost the same problem but on linux.

**Comment by hlineholm** [comment]
[Enter steps to reproduce:]

1. Open Atom by typing `atom .` in the terminal

**Atom**: 1.18.0 x64
**Electron**: 1.3.15
**OS**: Mac OS X 10.12.5
**Thrown From**: [atom-ctags](https://github.com/yongkangchen/atom-ctags) package 5.0.0


### Stack Trace

Failed to activate the atom-ctags package

```
At Cannot find module '/Applications/Atom.app/Contents/Resources/app.asar.unpacked/node_modules/ctags/build/Release/ctags.node'

Error: Cannot find module '/Applications/Atom.app/Contents/Resources/app.asar.unpacked/node_modules/ctags/build/Release/ctags.node'
    at Module._resolveFilename (module.js:455:15)
    at Module._resolveFilename (/Applications/Atom.app/Contents/Resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.get_Module._resolveFilename (/Applications/Atom.app/Contents/Resources/app/src/module-cache.js:354:58)
    at Module.require (Applications/Atom.app/Contents/Resources/app/static/index.js:40:43)
    at require (/Applications/Atom.app/Contents/Resources/app/src/native-compile-cache.js:66:33)
    at /packages/atom-ctags/node_modules/ctags/src/ctags.coffee:1:10)
    at /packages/atom-ctags/node_modules/ctags/src/ctags.coffee:1:1)
    at Module.get_Module._compile (/Applications/Atom.app/Contents/Resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .coffee] (/Applications/Atom.app/Contents/Resources/app/src/compile-cache.js:239:29)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (Applications/Atom.app/Contents/Resources/app/static/index.js:47:45)
    at require (/Applications/Atom.app/Contents/Resources/app/src/native-compile-cache.js:66:33)
    at /packages/atom-ctags/lib/ctags-cache.coffee:3:9)
    at /packages/atom-ctags/lib/ctags-cache.coffee:2:1)
    at Module.get_Module._compile (/Applications/Atom.app/Contents/Resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .coffee] (/Applications/Atom.app/Contents/Resources/app/src/compile-cache.js:239:29)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (Applications/Atom.app/Contents/Resources/app/static/index.js:47:45)
    at require (/Applications/Atom.app/Contents/Resources/app/src/native-compile-cache.js:66:33)
    at Object.activate (/packages/atom-ctags/lib/main.coffee:48:19)
    at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app/src/package.js:253:25)
    at /Applications/Atom.app/Contents/Resources/app/src/package.js:225:38
    at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app/src/package.js:99:21)
    at /Applications/Atom.app/Contents/Resources/app/src/package.js:218:32
    at Package.module.exports.Package.activate (/Applications/Atom.app/Contents/Resources/app/src/package.js:215:40)
    at PackageManager.module.exports.PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:645:40)
```

### Commands

```
  2x -0:55.6.0 tree-view:show (atom-workspace.workspace.scrollbars-visible-when-scrolling)
```

### Non-Core Packages

```
atom-ctags 5.0.0 
atom-ternjs 0.18.2 
autocomplete-modules 1.6.9 
busy-signal 1.3.0 
color-picker 2.2.5 
docblockr 0.9.4 
emmet 2.4.3 
eslint-fixer 1.2.1 
file-icons 2.1.2 
highlight-selected 0.13.1 
intentions 1.1.2 
language-plantuml 0.2.0 
linter 2.1.2 
linter-eslint 8.1.5 
linter-ui-default 1.2.2 
merge-conflicts 1.4.4 
minimap 4.27.1 
minimap-highlight-selected 4.6.1 
pigments 0.39.1 
plantuml-preview 0.12.9 
react 0.16.2 
todo-show 1.11.0 
```

**Comment by pvl1** [comment]
on my system, i did a search for the file and found it at /usr/lib/atom/node_modules/ctags/build/Release/ctags.node

**Comment by lomo1** [comment]
i have same issue on my mac.
Cannot find module
`/Applications/Atom.app/Contents/Resources/app/node_modules/ctags/build/Release/ctags.node`

**Comment by twlz0ne** [comment]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.21.0-beta0 x64
**Electron**: 1.6.9
**OS**: Mac OS X 10.11.6
**Thrown From**: [atom-ctags](https://github.com/yongkangchen/atom-ctags) package 5.1.0


### Stack Trace

Failed to activate the atom-ctags package

```
At Cannot find module '/Applications/Atom Beta.app/Contents/Resources/app/node_modules/ctags/build/Release/ctags.node'

Error: Cannot find module '/Applications/Atom Beta.app/Contents/Resources/app/node_modules/ctags/build/Release/ctags.node'
    at Module._resolveFilename (module.js:470:15)
    at Module._resolveFilename (/Applications/Atom Beta.app/Contents/Resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.get_Module._resolveFilename (/Applications/Atom Beta.app/Contents/Resources/app/src/module-cache.js:354:58)
    at Module.require (/app.asar/static/index.js:40:43)
    at require (/Applications/Atom Beta.app/Contents/Resources/app/src/native-compile-cache.js:66:33)
    at /packages/atom-ctags/node_modules/ctags/src/ctags.coffee:1:10)
    at /packages/atom-ctags/node_modules/ctags/src/ctags.coffee:1:1)
    at /packages/atom-ctags/node_modules/ctags/src/ctags.coffee:1:1)
    at Module.get_Module._compile (/Applications/Atom Beta.app/Contents/Resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .coffee] (/Applications/Atom Beta.app/Contents/Resources/app/src/compile-cache.js:239:29)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (/Applications/Atom Beta.app/Contents/Resources/app/src/native-compile-cache.js:66:33)
    at /packages/atom-ctags/lib/ctags-cache.coffee:3:9)
    at /packages/atom-ctags/lib/ctags-cache.coffee:2:1)
    at /packages/atom-ctags/lib/ctags-cache.coffee:2:1)
    at Module.get_Module._compile (/Applications/Atom Beta.app/Contents/Resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .coffee] (/Applications/Atom Beta.app/Contents/Resources/app/src/compile-cache.js:239:29)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (/Applications/Atom Beta.app/Contents/Resources/app/src/native-compile-cache.js:66:33)
    at Object.activate (/packages/atom-ctags/lib/main.coffee:48:19)
    at Package.module.exports.Package.activateNow (/Applications/Atom Beta.app/Contents/Resources/app/src/package.js:253:25)
    at /Applications/Atom Beta.app/Contents/Resources/app/src/package.js:225:38
    at Package.module.exports.Package.measure (/Applications/Atom Beta.app/Contents/Resources/app/src/package.js:99:21)
    at /Applications/Atom Beta.app/Contents/Resources/app/src/package.js:218:32
```

### Commands

```
```

### Non-Core Packages

```
asciidoc-preview 2.10.2 
atom-ctags 5.1.0 
atom-ide-ui 0.3.1 
atom-material-syntax 1.0.6 
atom-material-ui 2.0.4 
atom-ternjs 0.18.3 
autocomplete-python 1.10.2 
autoprefixer 3.7.1 
busy-signal 1.4.3 
color-picker 2.2.5 
csscomb 0.3.1 
csslint 1.1.5 
dracula-syntax 2.0.5 
dracula-theme 2.0.0 
dracula-ui 0.6.0 
emmet 2.4.3 
genesis-syntax 1.0.9 
genesis-ui 0.5.0 
highlight-line 0.12.0 
ide-flowtype 0.17.4 
ide-php 0.6.2 
intentions 1.1.5 
javascript-snippets 1.2.1 
language-asciidoc 1.10.0 
laravel 0.7.1 
linter 2.2.0 
linter-flake8 2.2.1 
linter-phpcs 1.6.7 
linter-pycodestyle 2.1.3 
linter-ui-default 1.6.8 
minimap 4.29.6 
nerd-treeview 0.5.4 
nucleus 0.3.0 
nuclide 0.252.0 
package-list 0.1.2 
php-integrator-symbol-viewer 0.6.4 
react 0.16.2 
seti-syntax 1.1.3 
seti-ui 1.9.0 
solarized-dark-ui 0.3.2 
trailing-spaces 0.4.0 
vim-mode 0.66.0 
Zen 0.18.0 
```

**Comment by heftyfunseeker** [comment]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.21.0-beta0 x64
**Electron**: 1.6.9
**OS**: Microsoft Windows 10 Pro
**Thrown From**: [atom-ctags](https://github.com/yongkangchen/atom-ctags) package 5.1.0


### Stack Trace

Failed to activate the atom-ctags package

```
At Cannot find module 'C:\Users\Nicco\AppData\Local\atom\app-1.21.0-beta0\resources/app/node_modules/ctags/build/Release/ctags.node'

Error: Cannot find module 'C:\Users\Nicco\AppData\Local\atom\app-1.21.0-beta0\resources/app/node_modules/ctags/build/Release/ctags.node'
  at Module._resolveFilename (module.js:470:15)
  at Module._resolveFilename (~/AppData/Local/atom/app-1.21.0-beta0/resources/electron.asar/common/reset-search-paths.js:35:12)
  at Function.get_Module._resolveFilename (<embedded>:11237:58)
  at Module.require (/app.asar/static/index.js:40:43)
  at require (<embedded>:10582:33)
  at /packages/atom-ctags/node_modules/ctags/src/ctags.coffee:1:10)
  at /packages/atom-ctags/node_modules/ctags/src/ctags.coffee:1:1)
  at /packages/atom-ctags/node_modules/ctags/src/ctags.coffee:1:1)
  at Module.get_Module._compile (<embedded>:10622:36)
  at Object.value [as .coffee] (<embedded>:10873:29)
  at Module.load (module.js:488:32)
  at tryModuleLoad (module.js:447:12)
  at Function.Module._load (module.js:439:3)
  at Module.require (/app.asar/static/index.js:47:45)
  at require (<embedded>:10582:33)
  at /packages/atom-ctags/lib/ctags-cache.coffee:3:9)
  at /packages/atom-ctags/lib/ctags-cache.coffee:2:1)
  at /packages/atom-ctags/lib/ctags-cache.coffee:2:1)
  at Module.get_Module._compile (<embedded>:10622:36)
  at Object.value [as .coffee] (<embedded>:10873:29)
  at Module.load (module.js:488:32)
  at tryModuleLoad (module.js:447:12)
  at Function.Module._load (module.js:439:3)
  at Module.require (/app.asar/static/index.js:47:45)
  at require (<embedded>:10582:33)
  at Object.activate (/packages/atom-ctags/lib/main.coffee:48:19)
  at Package.module.exports.Package.activateNow (<embedded>:69986:25)
  at <embedded>:69958:38
  at Package.module.exports.Package.measure (<embedded>:69832:21)
  at <embedded>:69951:32
  at Package.module.exports.Package.activate (<embedded>:69948:40)
  at PackageManager.activatePackage (<embedded>:23891:42)
  at config.transactAsync (<embedded>:23866:36)
  at Config.module.exports.Config.transactAsync (<embedded>:20789:24)
  at PackageManager.activatePackages (<embedded>:23864:23)
  at PackageManager.activate (<embedded>:23847:50)
  at <embedded>:1092:36

```

### Commands

```
```

### Non-Core Packages

```
atom-alignment 0.13.0 
atom-ctags 5.1.0 
atom-material-syntax 1.0.6 
atom-material-ui 2.0.4 
atom-perforce 1.7.11 
behave-theme 1.7.0 
better-jellybeans-syntax 1.0.3 
busy-signal 1.4.3 
choose-pane 0.7.0 
count-word 0.2.3 
cursor-history 0.12.0 
gruvbox 1.0.7 
intentions 1.1.5 
ir-black-syntax 0.2.0 
language-actionscript3 0.3.0 
language-elixir 0.20.2 
language-hlsl 1.2.0 
language-rust 0.4.12 
lazy-motion 0.7.0 
linter 2.2.0 
linter-rust 0.8.0 
linter-ui-default 1.6.10 
markdown-pdf 2.1.0 
markdown-writer 2.7.2 
oceanic-next 1.0.0 
paner 1.0.0 
project-folder 1.5.0 
project-plus 1.0.0 
relative-numbers 0.8.0 
release-notes 0.53.0 
scuba-steve 0.5.2 
sync-settings 0.8.3 
tool-bar 1.1.0 
vim-mode-plus 1.6.0 
vim-mode-plus-keymaps-for-surround 0.2.1 
vim-mode-plus-move-to-symbols 0.3.0 
zenburn 3.1.0 
zentabs 0.8.8 
```

**Comment by xHasKx** [comment]
I found a workaround (also maybe this will help to solve issue).

I edit first line of file ~/.atom/packages/atom-ctags/node_modules/ctags/src/ctags.coffee
`{Tags} = require(process.resourcesPath + '/app/node_modules/ctags/build/Release/ctags.node')`

to became like this:

`{Tags} = require(process.resourcesPath + '/app.asar.unpacked/node_modules/ctags/build/Release/ctags.node')`

because on my system:
```
$ find /usr/share/atom-beta/ -name ctags.node
/usr/share/atom-beta/resources/app.asar.unpacked/node_modules/ctags/build/Release/ctags.node
```

(note "app.asar.unpacked" in path)

**Comment by akapa100** [comment]
I have the same issue

**Comment by logictom** [comment]
Seeing the same issue here, Win 10

**Comment by Dayjo** [comment]
Also receiving this problem, same specs as one of the Mac's up there ^

**Comment by Shoes01** [comment]
Using Win7, @xHasKx's fix worked, but I also had to change the direction of the slashes. My tag line reads
`{Tags} = require(process.resourcesPath + '\\app.asar.unpacked\\node_modules\\ctags\\build\\Release\\ctags.node')`

**Comment by derwentx** [comment]
@xHasKx 's fix worked for me.

```
Atom: 1.21.0
Electron: 1.6.9
Chrome: 56.0.2924.87
Node: 7.4.0
Distro: OS X 10.12.6

Built-in Atom Packages (92)
├── atom-dark-syntax@0.28.0
├── atom-dark-ui@0.53.0
├── atom-light-syntax@0.29.0
├── atom-light-ui@0.46.0
├── base16-tomorrow-dark-theme@1.5.0
├── base16-tomorrow-light-theme@1.5.0
├── one-dark-ui@1.10.8
├── one-light-ui@1.10.8
├── one-dark-syntax@1.8.0
├── one-light-syntax@1.8.0
├── solarized-dark-syntax@1.1.2
├── solarized-light-syntax@1.1.2
├── about@1.7.8
├── archive-view@0.63.3
├── autocomplete-atom-api@0.10.3
├── autocomplete-css@0.17.3
├── autocomplete-html@0.8.1
├── autocomplete-plus@2.35.11
├── autocomplete-snippets@1.11.1
├── autoflow@0.29.0
├── autosave@0.24.3
├── background-tips@0.27.1
├── bookmarks@0.44.4
├── bracket-matcher@0.87.3
├── command-palette@0.41.1
├── dalek@0.2.1
├── deprecation-cop@0.56.9
├── dev-live-reload@0.47.1
├── encoding-selector@0.23.5
├── exception-reporting@0.41.4
├── find-and-replace@0.212.2
├── fuzzy-finder@1.5.8
├── github@0.6.2
├── git-diff@1.3.6
├── go-to-line@0.32.1
├── grammar-selector@0.49.5
├── image-view@0.62.3
├── incompatible-packages@0.27.3
├── keybinding-resolver@0.38.0
├── line-ending-selector@0.7.3
├── link@0.31.3
├── markdown-preview@0.159.13
├── metrics@1.2.6
├── notifications@0.69.2
├── open-on-github@1.2.1
├── package-generator@1.1.1
├── settings-view@0.251.8
├── snippets@1.1.4
├── spell-check@0.72.2
├── status-bar@1.8.13
├── styleguide@0.49.7
├── symbols-view@0.118.0 (disabled)
├── tabs@0.107.2
├── timecop@0.36.0
├── tree-view@0.217.9
├── update-package-dependencies@0.12.0
├── welcome@0.36.5
├── whitespace@0.37.3
├── wrap-guide@0.40.2
├── language-c@0.58.1
├── language-clojure@0.22.4
├── language-coffee-script@0.49.0
├── language-csharp@0.14.2
├── language-css@0.42.5
├── language-gfm@0.90.1
├── language-git@0.19.1
├── language-go@0.44.2
├── language-html@0.47.7
├── language-hyperlink@0.16.2
├── language-java@0.27.4
├── language-javascript@0.127.3
├── language-json@0.19.1
├── language-less@0.33.0
├── language-make@0.22.3
├── language-mustache@0.14.1
├── language-objective-c@0.15.1
├── language-perl@0.37.0
├── language-php@0.42.0
├── language-property-list@0.9.1
├── language-python@0.45.4
├── language-ruby@0.71.3
├── language-ruby-on-rails@0.25.2
├── language-sass@0.61.1
├── language-shellscript@0.25.3
├── language-source@0.9.0
├── language-sql@0.25.8
├── language-text@0.7.3
├── language-todo@0.29.2
├── language-toml@0.18.1
├── language-typescript@0.2.1
├── language-xml@0.35.2
└── language-yaml@0.30.2

Community Packages (63) /Users/derwent/.atom/packages
├── atom-beautify@0.30.5
├── atom-ctags@5.1.0
├── atom-html-preview@0.2.2
├── atom-macros@0.5.2
├── atom-python-virtualenv@0.14.0
├── autocomplete-clang@0.11.3
├── autocomplete-haskell@1.0.1
├── autocomplete-php@0.3.7
├── autocomplete-plus@2.36.2
├── build@0.69.0
├── busy@0.7.0
├── busy-signal@1.4.3 (disabled)
├── change-case@0.6.5
├── ctags-status@1.3.7
├── dash@1.7.1
├── editorconfig@2.2.2
├── file-icons@2.1.12
├── haskell-ghc-mod@2.1.1
├── haskell-grammar@0.4.0
├── hex-editor@0.1.1
├── ide-haskell@2.2.0
├── ide-haskell-cabal@2.0.3
├── intentions@1.1.5
├── join-lines-smarter@2.0.1
├── language-assembly@0.7.2
├── language-elm@1.5.0
├── language-haskell@1.14.2
├── language-htaccess@0.1.1
├── language-ini@1.19.0
├── language-lisp@0.2.0
├── language-lua@0.9.11
├── language-pfm@0.82.0
├── language-supercollider@0.2.1
├── language-tmux@0.4.0
├── language-viml@1.1.5
├── language-x86asm@0.9.0
├── linter@2.2.0
├── linter-gcc@0.7.1
├── linter-hlint@2.0.0
├── linter-php@1.5.1
├── linter-pylama@0.9.4
├── linter-pylint@2.1.0 (disabled)
├── linter-python@3.1.2 (disabled)
├── linter-ui-default@1.6.10
├── local-settings@0.4.1
├── markdown-preview-kramdown@0.5.3
├── markdown-preview-plus@2.4.10
├── minimap@4.29.7 (disabled)
├── minimap-linter@2.1.1
├── platformio-ide@2.0.0-rc.2 (disabled)
├── platformio-ide-debugger@1.2.4 (disabled)
├── platformio-ide-terminal@2.7.0
├── project-manager@3.3.5
├── python-indent@1.1.1
├── python-tools@0.6.9
├── python-yapf@0.14.0
├── script@3.16.0
├── set-syntax@0.4.0
├── sort-lines@0.15.0
├── split-and-move@0.2.1
├── split-diff@1.5.1
├── todo@0.6.0
└── tool-bar@1.1.0
```

**Comment by hadian90** [comment]
@xHasKx fix worked on my atom.

**Comment by hsandt** [comment]
@Shoes01 fix worked for Windows 10. This will need a fix in ctags.node generation. Looks like the asar folder was (re)introduced in Atom 1.21, following this discussion: https://github.com/atom/atom/pull/14682 and the symbols-view repository from which ctags is forked has already found the solution: https://github.com/atom/symbols-view/pull/226

I guess we are stuck until either an equivalent PR is made for ctags, or better, this repo merges changes from symbols-view, which is actually already on the TODO list.

**Comment by itrion** [comment]
@xHasKx fix also worked for me, tnx 

```
Atom    : 1.21.0
Electron: 1.6.9
Chrome  : 56.0.2924.87
Node    : 7.4.0
```

**Comment by pavanreddy61** [comment]
@xHasKx fix also worked for me, tnx Atom    : 1.21.0

**Comment by Dayjo** [comment]
I've not tried the fix, but I've moved over to using the new facebook-atom  `atom-ide-ui` package which seems to be doing essentially what this package was doing for me.

**Comment by harsh2327** [comment]
I had to do reverse of what @xHasKx mentioned [above](https://github.com/yongkangchen/atom-ctags/issues/192#issuecomment-330766418).

> I edit first line of file ~/.atom/packages/atom-ctags/node_modules/ctags/src/ctags.coffee
> {Tags} = require(process.resourcesPath + '/app/node_modules/ctags/build/Release/ctags.node')
> 
> to became like this:
> 
> {Tags} = require(process.resourcesPath + '/app.asar.unpacked/node_modules/ctags/build/Release/ctags.node')

I am on windows 7. Thanks @xHasKx!

**Comment by AJMaxwell** [comment]
[Enter steps to reproduce:]

1. Update atom-ctags
2. Restart Atom
3. See error

**Atom**: 1.19.0-beta4 x64
**Electron**: 1.6.9
**OS**: Ubuntu 16.04.3
**Thrown From**: [atom-ctags](https://github.com/yongkangchen/atom-ctags) package 5.1.2

I followed @xHasKx fix and got it working, though the directories were reversed for me.


### Stack Trace

Failed to activate the atom-ctags package

```
At Cannot find module '/usr/share/atom-beta/resources/app.asar.unpacked/node_modules/ctags/build/Release/ctags.node'

Error: Cannot find module '/usr/share/atom-beta/resources/app.asar.unpacked/node_modules/ctags/build/Release/ctags.node'
    at Module._resolveFilename (module.js:470:15)
    at Module._resolveFilename (/usr/share/atom-beta/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.get_Module._resolveFilename (/usr/share/atom-beta/resources/app/src/module-cache.js:354:58)
    at Module.require (usr/share/atom-beta/resources/app/static/index.js:40:43)
    at require (/usr/share/atom-beta/resources/app/src/native-compile-cache.js:66:33)
    at /packages/atom-ctags/node_modules/ctags/src/ctags.coffee:1:10)
    at /packages/atom-ctags/node_modules/ctags/src/ctags.coffee:1:1)
    at /packages/atom-ctags/node_modules/ctags/src/ctags.coffee:1:1)
    at Module.get_Module._compile (/usr/share/atom-beta/resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .coffee] (/usr/share/atom-beta/resources/app/src/compile-cache.js:239:29)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (usr/share/atom-beta/resources/app/static/index.js:47:45)
    at require (/usr/share/atom-beta/resources/app/src/native-compile-cache.js:66:33)
    at /packages/atom-ctags/lib/ctags-cache.coffee:3:9)
    at /packages/atom-ctags/lib/ctags-cache.coffee:2:1)
    at /packages/atom-ctags/lib/ctags-cache.coffee:2:1)
    at Module.get_Module._compile (/usr/share/atom-beta/resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .coffee] (/usr/share/atom-beta/resources/app/src/compile-cache.js:239:29)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (usr/share/atom-beta/resources/app/static/index.js:47:45)
    at require (/usr/share/atom-beta/resources/app/src/native-compile-cache.js:66:33)
    at Object.activate (/packages/atom-ctags/lib/main.coffee:48:19)
    at Package.module.exports.Package.activateNow (/usr/share/atom-beta/resources/app/src/package.js:253:25)
    at /usr/share/atom-beta/resources/app/src/package.js:225:38
    at Package.module.exports.Package.measure (/usr/share/atom-beta/resources/app/src/package.js:99:21)
    at /usr/share/atom-beta/resources/app/src/package.js:218:32
    at Package.module.exports.Package.activate (/usr/share/atom-beta/resources/app/src/package.js:215:40)
    at PackageManager.module.exports.PackageManager.activatePackage (/usr/share/atom-beta/resources/app/src/package-manager.js:645:40)
    at /usr/share/atom-beta/resources/app/src/package-manager.js:626:35
    at Config.module.exports.Config.transactAsync (/usr/share/atom-beta/resources/app/src/config.js:346:24)
    at PackageManager.module.exports.PackageManager.activatePackages (/usr/share/atom-beta/resources/app/src/package-manager.js:621:25)
    at PackageManager.module.exports.PackageManager.activate (/usr/share/atom-beta/resources/app/src/package-manager.js:603:52)
    at /usr/share/atom-beta/resources/app/src/atom-environment.js:843:36
```

### Commands

```
```

### Non-Core Packages

```
advanced-open-file 0.16.7 
atom-ctags 5.1.2 
atom-material-syntax 1.0.7 
atom-material-syntax-dark 1.0.0 
atom-material-ui 2.0.6 
busy-signal 1.4.3 
editorconfig 2.2.2 
emmet 2.4.3 
file-icons 2.1.13 
highlight-selected 0.13.1 
intentions 1.1.5 
language-blade 0.36.0 
language-powershell 4.0.0 
language-vue 0.23.1 
laravel 0.7.1 
lint-sass-vue 1.0.5 
linter 2.2.0 
linter-eslint 8.4.0 
linter-jscs 4.1.3 
linter-php 1.5.1 
linter-sass-lint 1.8.3 
linter-ui-default 1.6.10 
php-cs-fixer 4.1.1 
pigments 0.40.2 
vue2-autocomplete 0.1.0-alpha.4 
vuejs2-snippets 0.14.0 
```

**Comment by agoose77** [comment]
I've had this issue, and had to do the reverse of @xHasKx did, as @harsh2327 suggests, which *fixes* the issue

**Comment by kkraju4u** [comment]
Same for me too. Issue re-appeared a few days back. Reversed the previous fix (which is suggested by @xHasKx) and fixed the issue.

**Comment by mamanguy** [comment]
Same here thanks agoose77

**Comment by itgoyo** [comment]
thk@xHasKx 'ways ,it work for me

**Comment by ksangeek** [comment]
Thanks folks;
on my Mac i was getting this error -
﻿
![image](https://user-images.githubusercontent.com/19853088/33110584-d791d35a-cf6e-11e7-8ee3-27b00cdbdc0b.png)

And that was fixed by modifying contents of `~/.atom/packages/atom-ctags/node_modules/ctags/src/ctags.coffee` like this -
```
1c1
< {Tags} = require(process.resourcesPath + '/app.asar.unpacked/node_modules/ctags/build/Release/ctags.node')
---
> {Tags} = require(process.resourcesPath + '/app/node_modules/ctags/build/Release/ctags.node')
```
