### ISSUE TITLE
Failed to activate the atom-ctags package #192

### ISSUE THREAD

**Issue by GuaiLong618** [yongkangchen/atom-ctags#198]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.20.1 x64
**Electron**: 1.6.9
**OS**: Unknown Windows version
**Thrown From**: [atom-ctags](https://github.com/yongkangchen/atom-ctags) package 5.1.2

### Stack Trace

Failed to activate the atom-ctags package

```
At Cannot find module 'C:\Users\Zeus\AppData\Local\atom\app-1.20.1\resources/app.asar.unpacked/node_modules/ctags/build/Release/ctags.node'

Error: Cannot find module 'C:\Users\Zeus\AppData\Local\atom\app-1.20.1\resources/app.asar.unpacked/node_modules/ctags/build/Release/ctags.node'
    at Module._resolveFilename (module.js:470:15)
    at Module._resolveFilename (~/AppData/Local/atom/app-1.20.1/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.get_Module._resolveFilename (~/AppData/Local/atom/app-1.20.1/resources/app/src/module-cache.js:354:58)
    at Module.require (~/AppData/Local/atom/app-1.20.1/resources/app/static/index.js:40:43)
    at require (~/AppData/Local/atom/app-1.20.1/resources/app/src/native-compile-cache.js:66:33)
    at /packages/atom-ctags/node_modules/ctags/src/ctags.coffee:1:10)
    at /packages/atom-ctags/node_modules/ctags/src/ctags.coffee:1:1)
    at /packages/atom-ctags/node_modules/ctags/src/ctags.coffee:1:1)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.20.1/resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .coffee] (~/AppData/Local/atom/app-1.20.1/resources/app/src/compile-cache.js:239:29)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (~/AppData/Local/atom/app-1.20.1/resources/app/static/index.js:47:45)
    at require (~/AppData/Local/atom/app-1.20.1/resources/app/src/native-compile-cache.js:66:33)
    at /packages/atom-ctags/lib/ctags-cache.coffee:3:9)
    at /packages/atom-ctags/lib/ctags-cache.coffee:2:1)
    at /packages/atom-ctags/lib/ctags-cache.coffee:2:1)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.20.1/resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .coffee] (~/AppData/Local/atom/app-1.20.1/resources/app/src/compile-cache.js:239:29)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (~/AppData/Local/atom/app-1.20.1/resources/app/static/index.js:47:45)
    at require (~/AppData/Local/atom/app-1.20.1/resources/app/src/native-compile-cache.js:66:33)
    at Object.activate (/packages/atom-ctags/lib/main.coffee:48:19)
    at Package.module.exports.Package.activateNow (~/AppData/Local/atom/app-1.20.1/resources/app/src/package.js:253:25)
    at ~/AppData/Local/atom/app-1.20.1/resources/app/src/package.js:225:38
    at Package.module.exports.Package.measure (~/AppData/Local/atom/app-1.20.1/resources/app/src/package.js:99:21)
    at ~/AppData/Local/atom/app-1.20.1/resources/app/src/package.js:218:32
    at Package.module.exports.Package.activate (~/AppData/Local/atom/app-1.20.1/resources/app/src/package.js:215:40)
    at PackageManager.module.exports.PackageManager.activatePackage (~/AppData/Local/atom/app-1.20.1/resources/app/src/package-manager.js:645:40)
    at ~/AppData/Local/atom/app-1.20.1/resources/app/src/package-manager.js:377:25
    at ~/AppData/Local/atom/app-1.20.1/resources/app/src/config.js:693:26
    at Function.module.exports.Emitter.simpleDispatch (~/AppData/Local/atom/app-1.20.1/resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (~/AppData/Local/atom/app-1.20.1/resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at Config.module.exports.Config.emitChangeEvent (~/AppData/Local/atom/app-1.20.1/resources/app/src/config.js:884:35)
    at Config.module.exports.Config.setRawValue (~/AppData/Local/atom/app-1.20.1/resources/app/src/config.js:670:25)
    at Config.module.exports.Config.set (~/AppData/Local/atom/app-1.20.1/resources/app/src/config.js:248:20)
    at Config.module.exports.Config.removeAtKeyPath (~/AppData/Local/atom/app-1.20.1/resources/app/src/config.js:407:18)
    at Package.module.exports.Package.enable (~/AppData/Local/atom/app-1.20.1/resources/app/src/package.js:84:32)
    at PackageManager.module.exports.PackageManager.enablePackage (~/AppData/Local/atom/app-1.20.1/resources/app/src/package-manager.js:188:20)
    at HTMLButtonElement.enablementButtonClickHandler (~/AppData/Local/atom/app-1.20.1/resources/app/node_modules/settings-view/lib/package-card.js:361:31)
```

### Commands

```
     -6:10.2.0 core:paste (input.hidden-input)
  4x -5:48.6.0 intentions:highlight (input.hidden-input)
     -5:48 core:save (input.hidden-input)
     -5:45.1.0 window:save-all (input.hidden-input)
     -4:58.1.0 docblockr:parse-enter (input.hidden-input)
     -4:58.1.0 editor:newline (input.hidden-input)
     -4:57.8.0 intentions:highlight (input.hidden-input)
     -4:57.5.0 core:paste (input.hidden-input)
     -4:54.3.0 intentions:highlight (input.hidden-input)
     -4:54.1.0 editor:toggle-line-comments (input.hidden-input)
     -4:52.3.0 intentions:highlight (input.hidden-input)
     -4:51.9.0 core:save (input.hidden-input)
     -1:56.3.0 tree-view:expand-item (div.tool-panel.tree-view)
 26x -1:56 core:move-down (input.hidden-input)
     -0:50.1.0 atom-ctags:go-to-declaration (span.syntax--entity.syntax--name.syntax--function.syntax--c)
     -0:41.7.0 window:save-all (div.tool-panel.tree-view)
```

### Non-Core Packages

```
atom-beautify 0.30.6 
atom-ctags 5.1.2 
atom-ide-ui 0.6.0 
atom-typescript 11.0.10 
autocomplete-clang 0.11.4 
autocomplete-python 1.10.5 
busy-signal 1.4.3 
clang-format 1.29.0 
docblockr 0.13.2 
file-icons 2.1.14 
highlight-selected 0.13.1 
ide-typescript 0.1.6 
intentions 1.1.5 
kite 0.55.2 
linter 2.2.0 
linter-clang 4.1.2 
linter-flake8 2.2.1 
linter-ui-default 1.6.10 
minimap 4.29.7 
minimap-highlight-selected 4.6.1 
simplified-chinese-menu 5.3.5 
vim-mode 0.66.0 
```

**Comment by AaronDMarasco-VSI** [comment]
Same here, on Linux. Just upgraded w/ apm: "atom-ctags 5.1.0 -> 5.1.2"
```
$ atom --version
Atom    : 1.19.4
Electron: 1.6.9
Chrome  : 56.0.2924.87
Node    : 7.4.0
```

**Comment by aurovrata** [comment]
same problem here, using atom on linux, 
```
$ atom --version
Atom    : 1.22.1
Electron: 1.6.15
Chrome  : 56.0.2924.87
Node    : 7.4.0
```
atom-ctags v. 5.1.2

**Comment by johannfr** [comment]
Same here. Atom on Linux.
```
$ atom --version
Atom    : 1.18.0
Electron: 1.3.15
Chrome  : 52.0.2743.82
Node    : 6.5.0
```
Workaround:
`sudo ln -s /usr/share/atom/resources/app /usr/share/atom/resources/app.asar.unpacked`
