### ISSUE TITLE
Failed to activate the atom-ctags package

### ISSUE THREAD

**Issue by FrankSong28** [yongkangchen/atom-ctags#201]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.21.2 ia32
**Electron**: 1.6.15
**OS**: linux 4.13.11-1-ARCH
**Thrown From**: [atom-ctags](https://github.com/yongkangchen/atom-ctags) package 5.1.2

### Stack Trace

Failed to activate the atom-ctags package

```
At Arguments to CompositeDisposable.add must have a .dispose() method

TypeError: Arguments to CompositeDisposable.add must have a .dispose() method
    at assertDisposable (/usr/lib/atom/node_modules/event-kit/lib/composite-disposable.js:74:13)
    at CompositeDisposable.module.exports.CompositeDisposable.add (/usr/lib/atom/node_modules/event-kit/lib/composite-disposable.js:43:11)
    at Object.consumeProvider (/usr/lib/atom/node_modules/autocomplete-plus/lib/main.js:84:21)
    at Object.consumeProvider_2_0 (/usr/lib/atom/node_modules/autocomplete-plus/lib/main.js:61:17)
    at Provider.module.exports.Provider.provide (/usr/lib/atom/node_modules/service-hub/lib/provider.js:34:52)
    at ServiceHub.module.exports.ServiceHub.provide (/usr/lib/atom/node_modules/service-hub/lib/service-hub.js:30:20)
    at Package.module.exports.Package.activateServices (/usr/lib/atom/src/package.js:444:71)
    at Package.module.exports.Package.activateNow (/usr/lib/atom/src/package.js:254:16)
    at /usr/lib/atom/src/package.js:223:32
    at Package.module.exports.Package.measure (/usr/lib/atom/src/package.js:97:15)
    at /usr/lib/atom/src/package.js:216:26
    at Package.module.exports.Package.activate (/usr/lib/atom/src/package.js:213:34)
    at PackageManager.activatePackage (/usr/lib/atom/src/package-manager.js:679:36)
    at packagesToEnable.forEach.name (/usr/lib/atom/src/package-manager.js:428:45)
    at Array.forEach (native)
    at disabledPackagesSubscription.config.onDidChange (/usr/lib/atom/src/package-manager.js:428:24)
    at /usr/lib/atom/src/config.js:691:20
    at Function.module.exports.Emitter.simpleDispatch (/usr/lib/atom/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/usr/lib/atom/node_modules/event-kit/lib/emitter.js:141:28)
    at Config.module.exports.Config.emitChangeEvent (/usr/lib/atom/src/config.js:882:29)
    at Config.module.exports.Config.setRawValue (/usr/lib/atom/src/config.js:668:19)
    at Config.module.exports.Config.set (/usr/lib/atom/src/config.js:246:14)
    at Config.module.exports.Config.removeAtKeyPath (/usr/lib/atom/src/config.js:405:12)
    at Package.module.exports.Package.enable (/usr/lib/atom/src/package.js:82:26)
    at PackageManager.enablePackage (/usr/lib/atom/src/package-manager.js:234:12)
    at HTMLButtonElement.enablementButtonClickHandler (/usr/lib/atom/node_modules/settings-view/lib/package-card.js:353:25)
```

### Commands

```
     -3:09.3.0 atom-ctags:go-to-declaration (span.syntax--entity.syntax--name.syntax--function.syntax--c)
     -3:06.2.0 goto-definition:go (span.syntax--entity.syntax--name.syntax--function.syntax--c)
     -3:00.0 intentions:highlight (input.hidden-input)
     -2:59.8.0 symbols-tree-view:toggle (input.hidden-input)
     -2:47.9.0 line-ending-selector:show (atom-text-editor.editor.is-focused)
     -2:43.2.0 intentions:highlight (input.hidden-input)
     -2:42.8.0 symbols-tree-view:toggle (input.hidden-input)
     -2:31.9.0 editor:newline (input.hidden-input)
  7x -2:25.6.0 core:move-down (input.hidden-input)
     -2:24.2.0 autocomplete-plus:confirm (input.hidden-input)
 20x -2:22.4.0 core:backspace (input.hidden-input)
     -2:17.3.0 intentions:highlight (input.hidden-input)
     -2:17.2.0 core:save (input.hidden-input)
     -2:14.4.0 intentions:highlight (input.hidden-input)
     -2:12.4.0 atom-ctags:toggle-file-symbols (input.hidden-input)
  9x -2:07.6.0 core:backspace (input.hidden-input)
```

### Non-Core Packages

```
atom-beautify 0.30.9 
atom-ctags 5.1.2 
atom-sublime-monokai-syntax 0.4.4 
busy-signal 1.4.3 
goto-definition 1.3.4 
highlight-selected 0.13.1 
intentions 1.1.5 
linter 2.2.0 
linter-gcc 0.7.1 
linter-ui-default 1.6.10 
minimap 4.29.7 
minimap-find-and-replace 4.5.2 
minimap-highlight-selected 4.6.1 
Sublime-Style-Column-Selection 1.7.4 
symbols-tree-view 0.14.0 
```

**Comment by nefelim4ag** [comment]
Duplicated: #200 
Fixed for me like that:
/home/nefelim4ag/.atom/packages/atom-ctags/node_modules/ctags/src/ctags.coffee:
```
{Tags} = require('/home/nefelim4ag/.atom/packages/autocomplete-ctags/node_modules/ctags/build/Release/ctags.node')
```

**Comment by zioalex** [comment]
Same error for me:
`[Enter steps to reproduce:]

1. Install the package.
2. ...

**Atom**: 1.23.3 x64
**Electron**: 1.6.16
**OS**: "Sabayon Linux
**Thrown From**: [atom-ctags](https://github.com/yongkangchen/atom-ctags) package 5.1.2


### Stack Trace

Failed to activate the atom-ctags package

```
At Cannot find module '/usr/lib64/electron-1.6/resources/app.asar.unpacked/node_modules/ctags/build/Release/ctags.node'

Error: Cannot find module '/usr/lib64/electron-1.6/resources/app.asar.unpacked/node_modules/ctags/build/Release/ctags.node'
    at Module._resolveFilename (module.js:470:15)
    at Module._resolveFilename (/usr/lib64/electron-1.6/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._resolveFilename (/app.asar/src/module-cache.js:350:52)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (/app.asar/src/native-compile-cache.js:47:27)
    at /packages/atom-ctags/node_modules/ctags/src/ctags.coffee:1:10)
    at /packages/atom-ctags/node_modules/ctags/src/ctags.coffee:1:1)
    at /packages/atom-ctags/node_modules/ctags/src/ctags.coffee:1:1)
    at Module._compile (/app.asar/src/native-compile-cache.js:87:30)
    at /app.asar/src/compile-cache.js:234:23)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (/app.asar/src/native-compile-cache.js:47:27)
    at /packages/atom-ctags/lib/ctags-cache.coffee:3:9)
    at /packages/atom-ctags/lib/ctags-cache.coffee:2:1)
    at /packages/atom-ctags/lib/ctags-cache.coffee:2:1)
    at Module._compile (/app.asar/src/native-compile-cache.js:87:30)
    at /app.asar/src/compile-cache.js:234:23)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (/app.asar/src/native-compile-cache.js:47:27)
    at Object.activate (/packages/atom-ctags/lib/main.coffee:48:19)
    at Package.module.exports.Package.activateNow (/app.asar/src/package.js:253:19)
    at /app.asar/src/package.js:225:32
    at Package.module.exports.Package.measure (/app.asar/src/package.js:97:15)
    at /app.asar/src/package.js:218:26
    at Package.module.exports.Package.activate (/app.asar/src/package.js:215:34)
    at PackageManager.activatePackage (/app.asar/src/package-manager.js:690:36)
    at /app.asar/node_modules/settings-view/lib/package-manager.js:521:29
    at exit (/app.asar/node_modules/settings-view/lib/package-manager.js:114:16)
    at triggerExitCallback (/app.asar/src/buffered-process.js:322:11)
    at /app.asar/src/buffered-process.js:343:11
    at /app.asar/src/buffered-process.js:204:9)
    at emitOne (events.js:101:20)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:501:12)
```

### Commands

```
     -6:02.3.0 timecop:view (input.hidden-input)
     -5:01.3.0 command-palette:toggle (input.hidden-input)
 10x -4:54.6.0 core:move-down (input.hidden-input)
     -4:50.2.0 core:move-up (input.hidden-input)
     -4:48.3.0 core:confirm (input.hidden-input)
     -4:48.3.0 settings-view:install-packages-and-themes (input.hidden-input)
  2x -4:36.5.0 core:confirm (input.hidden-input)
```

### Non-Core Packages

```
atom-ctags 5.1.2 
atom-pair 2.0.13 
autocomplete-python 1.10.5 
language-terraform 0.8.1 
local-history 4.3.1 
platformio-ide-terminal 2.8.0 
revert-buffer 0.6.0 
terminal-plus 0.14.5 
vim-mode-plus 1.30.0 
```
`
I tried the solution proposed by @Nefelim4ag  but I don't have the ctags.node file in all my atom's tree.

**Comment by chenglongxu1** [comment]
I have the same issue. How to slove it?

[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.28.1 x64
**Electron**: 2.0.4
**OS**: Ubuntu 14.04.5
**Thrown From**: [atom-ctags](https://github.com/yongkangchen/atom-ctags) package 5.1.2


### Stack Trace

Failed to activate the atom-ctags package

```
At Arguments to CompositeDisposable.add must have a .dispose() method

TypeError: Arguments to CompositeDisposable.add must have a .dispose() method
    at assertDisposable (/usr/share/atom/resources/app/node_modules/event-kit/lib/composite-disposable.js:74:19)
    at CompositeDisposable.module.exports.CompositeDisposable.add (/usr/share/atom/resources/app/node_modules/event-kit/lib/composite-disposable.js:43:17)
    at Object.consumeProvider (/usr/share/atom/resources/app/node_modules/autocomplete-plus/lib/main.js:89:27)
    at Object.consumeProvider_2 (/usr/share/atom/resources/app/node_modules/autocomplete-plus/lib/main.js:62:23)
    at Provider.module.exports.Provider.provide (/usr/share/atom/resources/app/node_modules/service-hub/lib/provider.js:34:58)
    at ServiceHub.module.exports.ServiceHub.provide (/usr/share/atom/resources/app/node_modules/service-hub/lib/service-hub.js:30:26)
    at Package.activateServices (/usr/share/atom/resources/app/src/package.js:397:75)
    at Package.activateNow (/usr/share/atom/resources/app/src/package.js:233:20)
    at measure (/usr/share/atom/resources/app/src/package.js:206:33)
    at Package.measure (/usr/share/atom/resources/app/src/package.js:88:25)
    at activationPromise.Promise (/usr/share/atom/resources/app/src/package.js:200:20)
    at new Promise (<anonymous>)
    at Package.activate (/usr/share/atom/resources/app/src/package.js:198:38)
    at PackageManager.activatePackage (/usr/share/atom/resources/app/src/package-manager.js:695:42)
    at packagesToEnable.forEach.name (/usr/share/atom/resources/app/src/package-manager.js:440:51)
    at Array.forEach (<anonymous>)
    at disabledPackagesSubscription.config.onDidChange (/usr/share/atom/resources/app/src/package-manager.js:440:30)
    at emitter.on (/usr/share/atom/resources/app/src/config.js:1067:22)
    at Function.module.exports.Emitter.simpleDispatch (/usr/share/atom/resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (/usr/share/atom/resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at Config.emitChangeEvent (/usr/share/atom/resources/app/src/config.js:1226:62)
    at Config.endTransaction (/usr/share/atom/resources/app/src/config.js:882:16)
    at Config.transact (/usr/share/atom/resources/app/src/config.js:821:18)
    at Config._resetSettings (/usr/share/atom/resources/app/src/config.js:969:23)
    at Config.resetUserSettings (/usr/share/atom/resources/app/src/config.js:951:16)
    at disposables.add.applicationDelegate.onDidChangeUserSettings.settings (/usr/share/atom/resources/app/src/atom-environment.js:803:27)
    at EventEmitter.outerCallback (/usr/share/atom/resources/app/src/application-delegate.js:207:58)
    at emitThree (events.js:141:20)
    at EventEmitter.emit (events.js:217:7)
```

### Commands

```
     -2:15.9.0 snippets:expand (input.hidden-input)
     -2:15.9.0 editor:indent (input.hidden-input)
     -2:15.6.0 snippets:next-tab-stop (input.hidden-input)
     -2:15.6.0 snippets:expand (input.hidden-input)
     -2:15.6.0 editor:indent (input.hidden-input)
  3x -2:15.5.0 core:backspace (input.hidden-input)
     -2:14.8.0 snippets:next-tab-stop (input.hidden-input)
     -2:14.8.0 snippets:expand (input.hidden-input)
     -2:14.8.0 editor:indent (input.hidden-input)
  2x -2:13.1.0 core:backspace (input.hidden-input)
     -2:10.2.0 core:move-down (input.hidden-input)
     -2:09.5.0 core:move-up (input.hidden-input)
     -1:39.9.0 settings-view:open (ol.ftptree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -1:18.2.0 application:add-project-folder (span.name.icon.icon-file-directory)
  4x -0:13.9.0 core:backspace (input.hidden-input)
     -0:08.7.0 core:confirm (input.hidden-input)
```

### Non-Core Packages

```
atom-ctags 5.1.2 
autocomplete 0.47.0 
autocomplete-ctags 0.4.1 
remote-atom 1.3.12 
remote-ftp 2.2.0 
```

**Comment by sTiKyt** [comment]
Same: 
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.32.0 x64
**Electron**: 2.0.12
**OS**: "Arch Linux"
**Thrown From**: [atom-ctags](https://github.com/yongkangchen/atom-ctags) package 5.1.2


### Stack Trace

Failed to activate the atom-ctags package

```
At Cannot find module '/usr/lib/electron/resources/app.asar.unpacked/node_modules/ctags/build/Release/ctags.node'

Error: Cannot find module '/usr/lib/electron/resources/app.asar.unpacked/node_modules/ctags/build/Release/ctags.node'
    at Module._resolveFilename (module.js:543:15)
    at Module._resolveFilename (/usr/lib/electron/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._resolveFilename (/usr/lib/atom/src/module-cache.js:283:28)
    at Function.Module._load (module.js:473:25)
    at Module.require (module.js:586:17)
    at require (/usr/lib/atom/src/native-compile-cache.js:47:27)
    at /packages/atom-ctags/node_modules/ctags/src/ctags.coffee:1:10)
    at /packages/atom-ctags/node_modules/ctags/src/ctags.coffee:1:1)
    at /packages/atom-ctags/node_modules/ctags/src/ctags.coffee:1:1)
    at Module._compile (/usr/lib/atom/src/native-compile-cache.js:87:30)
    at Object.value [as .coffee] (/usr/lib/atom/src/compile-cache.js:235:23)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (module.js:586:17)
    at require (/usr/lib/atom/src/native-compile-cache.js:47:27)
    at /packages/atom-ctags/lib/ctags-cache.coffee:3:9)
    at /packages/atom-ctags/lib/ctags-cache.coffee:2:1)
    at /packages/atom-ctags/lib/ctags-cache.coffee:2:1)
    at Module._compile (/usr/lib/atom/src/native-compile-cache.js:87:30)
    at Object.value [as .coffee] (/usr/lib/atom/src/compile-cache.js:235:23)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (module.js:586:17)
    at require (/usr/lib/atom/src/native-compile-cache.js:47:27)
    at Object.activate (/packages/atom-ctags/lib/main.coffee:48:19)
    at Package.activateNow (/usr/lib/atom/src/package.js:224:27)
    at measure (/usr/lib/atom/src/package.js:200:27)
    at Package.measure (/usr/lib/atom/src/package.js:82:19)
```

### Commands

```
```

### Non-Core Packages

```
atom-ctags 5.1.2 
atom-html-preview 0.2.5 
reindent 1.5.0 
```

**Comment by barbestack** [comment]
Same. I installed autocomplete-ctags in case it helped to have that package present before installing atom-ctags, but didn't matter. Got the failure to activate.

Atom: 1.45.0 x64
OS: Darwin Version 18.7.0
atom-ctags 5.1.2

```
Error: Module did not self-register.
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:160:31)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:722:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:160:31)
    at Module.load (internal/modules/cjs/loader.js:602:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:541:12)
    at Function.Module._load (internal/modules/cjs/loader.js:533:3)
    at Module.require (file:///Applications/Atom.app/Contents/Resources/app.asar/static/index.js:72:46)
    at require (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:146745)
    at Object.<anonymous> (/Users/barbe/.atom/packages/atom-ctags/node_modules/ctags/src/ctags.coffee:1:10)
    at Object.<anonymous> (/Users/barbe/.atom/packages/atom-ctags/node_modules/ctags/src/ctags.coffee:1:1)
    at Object.<anonymous> (/Users/barbe/.atom/packages/atom-ctags/node_modules/ctags/src/ctags.coffee:1:1)
    at Module.get_Module._compile (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:147429)
    at Object.value [as .coffee] (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:150977)
    at Module.load (internal/modules/cjs/loader.js:602:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:541:12)
    at Function.Module._load (internal/modules/cjs/loader.js:533:3)
    at Module.require (file:///Applications/Atom.app/Contents/Resources/app.asar/static/index.js:72:46)
    at require (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:146745)
    at Object.<anonymous> (/Users/barbe/.atom/packages/atom-ctags/lib/ctags-cache.coffee:3:9)
    at Object.<anonymous> (/Users/barbe/.atom/packages/atom-ctags/lib/ctags-cache.coffee:2:1)
    at Object.<anonymous> (/Users/barbe/.atom/packages/atom-ctags/lib/ctags-cache.coffee:2:1)
    at Module.get_Module._compile (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:147429)
    at Object.value [as .coffee] (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:150977)
    at Module.load (internal/modules/cjs/loader.js:602:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:541:12)
    at Function.Module._load (internal/modules/cjs/loader.js:533:3)
    at Module.require (file:///Applications/Atom.app/Contents/Resources/app.asar/static/index.js:72:46)
    at require (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:146745)
    at Object.activate (/Users/barbe/.atom/packages/atom-ctags/lib/main.coffee:48:19)
    at Package.activateNow (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:3221925)
    at measure (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:3221337)
    at Package.measure (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:3218947)
    at activationPromise.activationPromise.Promise (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:3221197)
    at new Promise (<anonymous>)
    at Package.activate (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:3221140)
    at PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:382452)
    at /Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:942215
    at r (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:936821)
    at n (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:14:1125033)
    at ChildProcess.o.process.on.e (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:14:1125239)
    at ChildProcess.emit (events.js:182:13)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:240:12)
```
