### ISSUE TITLE
Uncaught Error: Could not resolve 'autocomplete-plus' to a package path

### ISSUE THREAD

**Issue by freiden** [yongkangchen/atom-ctags#46]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.165.0
**System**: Mac OS X 10.10.1
**Thrown From**: [atom-ctags](https://github.com/yongkangchen/atom-ctags) package, v2.5.5

### Stack Trace

Uncaught Error: Could not resolve 'autocomplete-plus' to a package path

```
At /Applications/Atom.app/Contents/Resources/app/src/package-manager.js:347

Error: Could not resolve 'autocomplete-plus' to a package path
  at PackageManager.module.exports.PackageManager.loadPackage (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:347:15)
  at PackageManager.module.exports.PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:409:21)
  at Object.module.exports.activate (/Users/charles/.atom/packages/atom-ctags/lib/ctags-complete.coffee:9:19)
  at /Users/charles/.atom/packages/atom-ctags/lib/main.coffee:17:35

```

### Commands

```
     -0:04.2 core:backspace (input.hidden-input)
     -0:00.0 core:confirm (input.hidden-input)
```

### Config

```
{
  "core": {
    "disabledPackages": [
      "symbols-view"
    ]
  }
}
```

### Installed Packages

```coffee
# User
atom-ctags, v2.5.5

# Dev
No dev packages
```

/cc @atom/core

**Comment by noseglid** [comment]
Did you install autocomplete-plus [as stated in the readme under `install`](https://github.com/yongkangchen/atom-ctags#install) ?
