### ISSUE TITLE
Uncaught TypeError: Cannot read property 'trim' of undefined

### ISSUE THREAD

**Issue by panqiushi** [yongkangchen/atom-ctags#55]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.176.0
**System**: Mac OS X 10.10.1
**Thrown From**: [atom-ctags](https://github.com/yongkangchen/atom-ctags) package, v2.5.5

### Stack Trace

Uncaught TypeError: Cannot read property 'trim' of undefined

```
At /Users/QA/.atom/packages/atom-ctags/lib/tag-generator.coffee:103

TypeError: Cannot read property 'trim' of undefined
  at TagGenerator.module.exports.TagGenerator.generate (/Users/QA/.atom/packages/atom-ctags/lib/tag-generator.coffee:103:48)
  at Object.module.exports.generateTags (/Users/QA/.atom/packages/atom-ctags/lib/ctags-cache.coffee:61:61)
  at Object.module.exports.getOrCreateTags (/Users/QA/.atom/packages/atom-ctags/lib/ctags-cache.coffee:78:6)
  at FileView.module.exports.FileView.populate (/Users/QA/.atom/packages/atom-ctags/lib/file-view.coffee:103:17)
  at FileView.module.exports.FileView.toggle (/Users/QA/.atom/packages/atom-ctags/lib/file-view.coffee:44:8)
  at atom-workspace.<anonymous> (/Users/QA/.atom/packages/atom-ctags/lib/main.coffee:10:5)
  at atom-workspace.handler (/Applications/Atom.app/Contents/Resources/app/src/space-pen-extensions.js:115:32)
  at atom-workspace.jQuery.event.dispatch (/Applications/Atom.app/Contents/Resources/app/node_modules/space-pen/vendor/jquery.js:4681:9)
  at atom-workspace.elemData.handle (/Applications/Atom.app/Contents/Resources/app/node_modules/space-pen/vendor/jquery.js:4359:46)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:243:29)
  at /Applications/Atom.app/Contents/Resources/app/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:558:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:396:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/Applications/Atom.app/Contents/Resources/app/src/window-event-handler.js:170:20)

```

### Commands

```
  6x -0:38.4 vim-mode:move-down (atom-text-editor.editor.vim-mode.command-mode)
  5x -0:37.6 vim-mode:move-right (atom-text-editor.editor.vim-mode.command-mode)
     -0:36.0 vim-mode:move-down (atom-text-editor.editor.vim-mode.command-mode)
  7x -0:32.9 vim-mode:search-current-word (atom-text-editor.editor.vim-mode.command-mode)
  2x -0:30.6 vim-mode:bracket-matching-motion (atom-text-editor.editor.vim-mode.command-mode)
  4x -0:29.6 vim-mode:move-to-last-character-of-line (atom-text-editor.editor.vim-mode.command-mode)
     -0:28.2 vim-mode:delete (atom-text-editor.editor.vim-mode.command-mode)
  3x -0:28.0 vim-mode:move-down (atom-text-editor.editor.vim-mode.command-mode)
     -0:27.0 vim-mode:reset-command-mode (atom-text-editor.editor.vim-mode.command-mode)
  2x -0:26.9 vim-mode:undo (atom-text-editor.editor.vim-mode.command-mode)
     -0:26.0 vim-mode:reset-command-mode (atom-text-editor.editor.vim-mode.command-mode)
 21x -0:25.8 vim-mode:move-down (atom-text-editor.editor.vim-mode.command-mode)
     -0:13.0 window:toggle-full-screen (atom-text-editor.editor.vim-mode.command-mode)
  2x -0:06.6 vim-mode:reset-command-mode (atom-text-editor.editor.vim-mode.command-mode)
 17x -0:06.2 vim-mode:move-down (atom-text-editor.editor.vim-mode.command-mode)
     -0:02.7 atom-ctags:toggle-file-symbols (atom-text-editor.editor.vim-mode.command-mode)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "symbols-view"
    ],
    "themes": [
      "one-dark-ui",
      "one-dark-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
atom-ctags, v2.5.5
autocomplete-plus, v1.1.0
color-picker, v1.4.4
command-logger, v0.22.0
editor-stats, v0.16.0
file-icons, v1.4.8
linter, v0.10.1
travis-ci-status, v0.11.2
vim-mode, v0.30.0

# Dev
No dev packages
```

/cc @atom/core

**Comment by yongkangchen** [comment]
sorry, I cannot reproduce.
