### ISSUE TITLE
Failed to activate the atom-ctags package

### ISSUE THREAD

**Issue by kjusupov** [yongkangchen/atom-ctags#74]
[Enter steps to reproduce below:]

1. Start atom in emulation mode (atom --one)

**Atom Version**: 0.190.0
**System**: Mac OS X 10.10.2
**Thrown From**: [atom-ctags](https://github.com/yongkangchen/atom-ctags) package, v2.6.1

### Stack Trace

Failed to activate the atom-ctags package

```
At undefined is not a function

TypeError: undefined is not a function
    at Object.module.exports.activate (/Users/kjusupov/.atom/packages/atom-ctags/lib/main.coffee:41:26)
    at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app/src/package.js:225:19)
    at /Applications/Atom.app/Contents/Resources/app/src/package.js:206:30
    at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app/src/package.js:152:15)
    at Package.module.exports.Package.activate (/Applications/Atom.app/Contents/Resources/app/src/package.js:199:14)
    at PackageManager.module.exports.PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:435:21)
    at /Applications/Atom.app/Contents/Resources/app/src/package-manager.js:419:29
    at Config.module.exports.Config.transact (/Applications/Atom.app/Contents/Resources/app/src/config.js:302:16)
    at PackageManager.module.exports.PackageManager.activatePackages (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:414:19)
    at PackageManager.module.exports.PackageManager.activate (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:395:46)
```

### Commands

```
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "language-java",
      "language-objective-c",
      "language-ruby-on-rails",
      "language-c",
      "language-clojure",
      "language-go",
      "symbols-view",
      "atom-beautify"
    ],
    "projectHome": "/Users/kjusupov/development/"
  },
  "atom-ctags": {
    "autoBuildTagsWhenActive": true,
    "buildTimeout": 30000,
    "cmd": "/usr/local/bin/ctags",
    "cmdArgs": "--exclude=.git --exclude=app/vendor --exclude=app/environments --exclude=app/frontend/web --exclude=app/frontend/runtime --exclude=app/backend/web --exclude=app/backend/runtime -R ."
  }
}
```

### Installed Packages

```coffee
# User
atom-ctags, v2.6.1
autocomplete-plus, v2.9.0
linter, v0.12.0
open-last-project, v0.3.5
project-manager, v1.15.5
symbols-tree-view, v0.9.1

# Dev
No dev packages
```

**Comment by yongkangchen** [comment]
Fixed by upgrade to use atom api of 1.0

**Comment by KevinBongart** [comment]
Fresh install of Atom yesterday, upgraded to 1.0 today, decided to install atom-ctags 4.1.4 and got this error: `Module did not self-register.`

It's installed though, and if I restart Atom, atom-ctags disables and replace symbols-view, but trying to go to a method definition I get this error thrown from symbols-view package:

```javascript
Module did not self-register.
ATOM_SHELL_ASAR.js:118
Hide Stack Trace
Error: Module did not self-register.
  at Error (native)
  at Object.module.(anonymous function) (ATOM_SHELL_ASAR.js:118:20)
  at Object.module.(anonymous function) [as .node] (ATOM_SHELL_ASAR.js:129:18)
  at Module.load (module.js:347:32)
  at Function.Module._load (module.js:302:12)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at Object.<anonymous> (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/node_modules/symbols-view/node_modules/ctags/lib/ctags.js:4:10)
  at Object.<anonymous> (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/node_modules/symbols-view/node_modules/ctags/lib/ctags.js:60:4)
  at Module._compile (module.js:452:26)
  at Object.loadFile [as .js] (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/src/babel.js:162:21)
  at Module.load (module.js:347:32)
  at Function.Module._load (module.js:302:12)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at Object.<anonymous> (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/node_modules/symbols-view/lib/tag-reader.js:6:11)
  at Object.<anonymous> (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/node_modules/symbols-view/lib/tag-reader.js:66:4)
  at Module._compile (module.js:452:26)
  at Object.loadFile [as .js] (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/src/babel.js:162:21)
  at Module.load (module.js:347:32)
  at Function.Module._load (module.js:302:12)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at Object.<anonymous> (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/node_modules/symbols-view/lib/go-to-view.js:12:15)
  at Object.<anonymous> (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/node_modules/symbols-view/lib/go-to-view.js:83:4)
  at Module._compile (module.js:452:26)
  at Object.loadFile [as .js] (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/src/babel.js:162:21)
  at Module.load (module.js:347:32)
  at Function.Module._load (module.js:302:12)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at Object.module.exports.createGoToView (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/node_modules/symbols-view/lib/main.js:81:20)
  at atom-text-editor.editorSubscription.atom.commands.add.symbols-view:go-to-declaration (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/node_modules/symbols-view/lib/main.js:26:26)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/src/command-registry.js:241:29)
  at /opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:520:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:355:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:180:20)
```

**Comment by KevinBongart** [comment]
I did another fresh install, this time by cleaning up everything I could find about Atom and the package did register. :tada:

**Comment by powercandy** [comment]
help me!
Failed to activate the atom-miku package
Error: Cannot find module 'jquery'
    at Module._resolveFilename (module.js:455:15)
    at Module._resolveFilename (C:\Users\Administrator\AppData\Local\atom\app-1.15.0\resources\electron.asar\common\reset-search-paths.js:35:12)
    at Function.Module._resolveFilename (C:\Users\Administrator\AppData\Local\atom\app-1.15.0\resources\app.asar\src\module-cache.js:383:52)
    at Function.Module._load (module.js:403:25)
    at Module.require (module.js:483:17)
    at require (C:\Users\Administrator\AppData\Local\atom\app-1.15.0\resources\app.asar\src\native-compile-cache.js:50:27)
    at Object.<anonymous> (C:\Users\Administrator\.atom\packages\atom-miku-master\lib\main.js:2:9)
    at Module._compile (C:\Users\Administrator\AppData\Local\atom\app-1.15.0\resources\app.asar\src\native-compile-cache.js:109:30)
    at Object.value [as .js] (C:\Users\Administrator\AppData\Local\atom\app-1.15.0\resources\app.asar\src\compile-cache.js:216:21)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (C:\Users\Administrator\AppData\Local\atom\app-1.15.0\resources\app.asar\src\native-compile-cache.js:50:27)
    at Package.module.exports.Package.requireMainModule (C:\Users\Administrator\AppData\Local\atom\app-1.15.0\resources\app.asar\src\package.js:796:27)
    at Package.module.exports.Package.activateNow (C:\Users\Administrator\AppData\Local\atom\app-1.15.0\resources\app.asar\src\package.js:207:16)
    at C:\Users\Administrator\AppData\Local\atom\app-1.15.0\resources\app.asar\src\package.js:876:25
    at Function.module.exports.Emitter.simpleDispatch (C:\Users\Administrator\AppData\Local\atom\app-1.15.0\resources\app.asar\node_modules\event-kit\lib\emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (C:\Users\Administrator\AppData\Local\atom\app-1.15.0\resources\app.asar\node_modules\event-kit\lib\emitter.js:129:28)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (C:\Users\Administrator\AppData\Local\atom\app-1.15.0\resources\app.asar\src\command-registry.js:240:20)
    at CommandRegistry.handleCommandEvent (C:\Users\Administrator\AppData\Local\atom\app-1.15.0\resources\app.asar\src\command-registry.js:3:59)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (C:\Users\Administrator\AppData\Local\atom\app-1.15.0\resources\app.asar\src\command-registry.js:160:19)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchContextMenuCommand (C:\Users\Administrator\AppData\Local\atom\app-1.15.0\resources\app.asar\src\atom-environment.js:1168:28)
    at EventEmitter.outerCallback (C:\Users\Administrator\AppData\Local\atom\app-1.15.0\resources\app.asar\src\application-delegate.js:325:25)
    at emitThree (events.js:116:13)
    at EventEmitter.emit (events.js:194:7)
