### ISSUE TITLE
Failed to load the atom-ctags package

### ISSUE THREAD

**Issue by Rambomst** [yongkangchen/atom-ctags#79]
[Enter steps to reproduce below:]

Step 1. Install atom-ctags...

**Atom Version**: 0.194.0
**System**: Mac OS X 10.10.3
**Thrown From**: [atom-ctags](https://github.com/yongkangchen/atom-ctags) package, v2.7.0

### Stack Trace

Failed to load the atom-ctags package

```
At Cannot find module 'atom-space-pen-views'

Error: Cannot find module 'atom-space-pen-views'
  at Module._resolveFilename (module.js:328:15)
  at Function.Module._resolveFilename (/Applications/Atom.app/Contents/Resources/app.asar/src/module-cache.js:383:52)
  at Function.Module._load (module.js:270:25)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at Object.<anonymous> (/Users/patrick/.atom/packages/atom-ctags/lib/main.coffee:1:7)
  at Object.<anonymous> (/Users/patrick/.atom/packages/atom-ctags/lib/main.coffee:1:1)
  at Module._compile (module.js:452:26)
  at Object.requireCoffeeScript (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/coffee-cash/lib/coffee-cash.js:85:19)
  at Module.load (module.js:347:32)
  at Function.Module._load (module.js:302:12)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at Package.module.exports.Package.requireMainModule (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:677:34)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:170:28
  at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:147:15)
  at Package.module.exports.Package.load (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:161:12)
  at PackageManager.module.exports.PackageManager.loadPackage (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:354:14)
  at PackageManager.module.exports.PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:433:30)
  at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-manager.js:276:29
  at exit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-manager.js:43:16)
  at BufferedProcess.triggerExitCallback (/Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:63:47)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:77:18
  at Socket.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:150:18)
  at emitOne (events.js:82:20)
  at Socket.emit (events.js:166:7)
  at Pipe.close (net.js:464:12)

```

### Commands

```
  2x -6:09.1.0 core:delete (atom-text-editor.editor.is-focused)
     -6:07.1.0 core:save (atom-text-editor.editor.is-focused)
     -2:47.7.0 symbols-view:go-to-declaration (atom-text-editor.editor)
     -0:43.5.0 core:paste (atom-text-editor.editor.mini)
     -0:43.1.0 core:confirm (atom-text-editor.editor.mini)
```

### Config

```json
{
  "core": {}
}
```

### Installed Packages

```coffee
# User
Sublime-Style-Column-Selection, v1.2.3
atom-ctags, v2.7.0
autocomplete-css, v0.6.0
autocomplete-plus, v2.12.0
file-icons, v1.5.4
file-types, v0.3.0
highlight-selected, v0.9.2
language-smarty-php, v0.5.0
linter, v0.12.1
linter-csslint, v0.0.11
linter-js-yaml, v1.0.0
linter-less, v0.3.1
linter-php, v0.0.12
minimap, v4.7.6
sync-settings, v0.2.2

# Dev
No dev packages
```

**Comment by fibric** [comment]
**Atom Version**: 0.194.0
**System**: Microsoft Windows 7 Enterprise 
**Thrown From**: [atom-ctags](https://github.com/yongkangchen/atom-ctags) package, v2.7.0

### Stack Trace

Failed to load the atom-ctags package

```
At Cannot find module 'atom-space-pen-views'

Error: Cannot find module 'atom-space-pen-views'
    at Module._resolveFilename (module.js:328:15)
    at Function.Module._resolveFilename (C:\Users\denny.trebbin\AppData\Local\atom\app-0.194.0\resources\app.asar\src\module-cache.js:383:52)
    at Function.Module._load (module.js:270:25)
    at Module.require (module.js:357:17)
    at require (module.js:376:17)
    at Object.<anonymous> (C:\Users\denny.trebbin\.atom\packages\atom-ctags\lib\main.coffee:4:7)
    at Object.<anonymous> (C:\Users\denny.trebbin\.atom\packages\atom-ctags\lib\main.coffee:166:4)
    at Module._compile (module.js:452:26)
    at Object.requireCoffeeScript (C:\Users\denny.trebbin\AppData\Local\atom\app-0.194.0\resources\app.asar\node_modules\coffee-cash\lib\coffee-cash.js:85:19)
    at Module.load (module.js:347:32)
```

### Commands

```
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "symbols-view",
      "linter-flow"
    ],
    "themes": [
      "newton-dark-ui",
      "newton-dark-syntax"
    ],
    "audioBeep": false,
    "autoHideMenuBar": true
  }
}
```

### Installed Packages

```coffee
# User
atom-ctags, v2.7.0
atom-ternjs, v0.5.23
autocomplete-bibtex, v0.5.6
autocomplete-paths, v1.0.2
autocomplete-plus, v2.12.0
git-tab-status, v1.7.0
highlight-column, v0.4.0
highlight-line, v0.10.2
highlight-selected, v0.9.2
linter, v0.12.1
linter-coffeelint, v0.2.1
linter-csslint, v0.0.11
linter-eslint, v0.5.2
linter-jsonlint, v0.1.2
linter-stylint, v0.5.0
newton-dark-syntax, v1.1.1
newton-dark-ui, v1.0.4
pigments, v0.1.2
preview-plus, v1.1.19
project-manager, v1.15.5
project-palette-finder, v2.4.17
save-session, vundefined
text-manipulation, v0.4.0

# Dev
No dev packages
```

**Comment by fibric** [comment]
uninstalling and reinstalling does not solve the issue.
rebuilding modules cache also does not solve the issue.

**Comment by npassaro** [comment]
:+1:

**Comment by patrickgilmour** [comment]
+1

**Comment by theblacklion** [comment]
:chocolate_bar:
