### ISSUE TITLE
Uncaught TypeError: Cannot convert undefined or null to object

### ISSUE THREAD

**Issue by CloneXpert** [yongkangchen/atom-ctags#85]
1. Install atom-ctags
2. Try to save any file

Could  be because of my username: "Tamás" ?

**Atom Version**: 0.199.0
**System**: Microsoft Windows 8.1 Pro N
**Thrown From**: [atom-ctags](https://github.com/yongkangchen/atom-ctags) package, v3.2.0

### Stack Trace

Uncaught TypeError: Cannot convert undefined or null to object

```
At C:\Users\Tamás\AppData\Local\atom\app-0.199.0\resources\app.asar\src\pane.js:759

TypeError: Cannot convert undefined or null to object
  at Object.module.exports.generateTags (C:\Users\Tamás\.atom\packages\atom-ctags\lib\ctags-cache.coffee:51:24)
  at C:\Users\Tamás\.atom\packages\atom-ctags\lib\file-view.coffee:15:23
  at Emitter.module.exports.Emitter.emit (C:\Users\Tamás\AppData\Local\atom\app-0.199.0\resources\app.asar\node_modules\event-kit\lib\emitter.js:82:11)
  at TextBuffer.module.exports.TextBuffer.saveAs (C:\Users\Tamás\AppData\Local\atom\app-0.199.0\resources\app.asar\node_modules\text-buffer\lib\text-buffer.js:917:20)
  at TextBuffer.module.exports.TextBuffer.save (C:\Users\Tamás\AppData\Local\atom\app-0.199.0\resources\app.asar\node_modules\text-buffer\lib\text-buffer.js:899:19)
  at TextEditor.module.exports.TextEditor.save (C:\Users\Tamás\AppData\Local\atom\app-0.199.0\resources\app.asar\src\text-editor.js:567:26)
  at Pane.module.exports.Pane.saveItem (C:\Users\Tamás\AppData\Local\atom\app-0.199.0\resources\app.asar\src\pane.js:523:18)
  at Pane.module.exports.Pane.saveActiveItem (C:\Users\Tamás\AppData\Local\atom\app-0.199.0\resources\app.asar\src\pane.js:506:19)
  at Workspace.module.exports.Workspace.saveActivePaneItem (C:\Users\Tamás\AppData\Local\atom\app-0.199.0\resources\app.asar\src\workspace.js:585:35)
  at atom-workspace.atom.commands.add.core:save (C:\Users\Tamás\AppData\Local\atom\app-0.199.0\resources\app.asar\src\workspace-element.js:310:30)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (C:\Users\Tamás\AppData\Local\atom\app-0.199.0\resources\app.asar\src\command-registry.js:238:29)
  at C:\Users\Tamás\AppData\Local\atom\app-0.199.0\resources\app.asar\src\command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (C:\Users\Tamás\AppData\Local\atom\app-0.199.0\resources\app.asar\node_modules\atom-keymap\lib\keymap-manager.js:519:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (C:\Users\Tamás\AppData\Local\atom\app-0.199.0\resources\app.asar\node_modules\atom-keymap\lib\keymap-manager.js:354:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (C:\Users\Tamás\AppData\Local\atom\app-0.199.0\resources\app.asar\src\window-event-handler.js:178:20)

```

### Commands

```
     -9:05.7.0 core:cut (atom-text-editor.editor.is-focused)
     -9:05.3.0 core:save (atom-text-editor.editor.is-focused)
     -1:49.8.0 editor:newline (atom-text-editor.editor.is-focused)
  7x -1:47.9.0 core:backspace (atom-text-editor.editor.is-focused)
     -1:33.8.0 editor:newline (atom-text-editor.editor.is-focused.autocomplete-active)
  2x -1:31.2.0 core:backspace (atom-text-editor.editor.is-focused.autocomplete-active)
     -1:29.6.0 autocomplete-plus:cancel (atom-text-editor.editor.is-focused.autocomplete-active)
  7x -1:27.9.0 core:save (atom-text-editor.editor.is-focused)
     -1:16.9.0 settings-view:open (div.am-panel.tool-panel.panel-bottom.native-key-bindings)
  2x -1:13.3.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -1:12.2.0 editor:delete-to-beginning-of-word (atom-text-editor.editor.mini.is-focused)
     -1:12.1.0 core:backspace (atom-text-editor.editor.mini.is-focused)
  5x -0:12.1.0 core:close (div.package-readme.native-key-bindings)
     -0:03.4.0 core:save (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "autocomplete-paths",
      "symbols-view",
      "atom-ctags"
    ]
  }
}
```

### Installed Packages

```coffee
# User
color-picker, v1.7.0
error-status, v0.3.3
meteor-api, v2.19.0

# Dev
No dev packages
```

**Comment by yongkangchen** [comment]
Is this issues still exist after restart atom ?

**Comment by yongkangchen** [comment]
I guess it has something to do with your username  `Tamás`, would you mind move this issue to https://github.com/atom/atom ?

**Comment by ainstushar** [comment]
Just happened this on my end. I don't have any unusual names.

````
C:\Users\tpatel\AppData\Local\atom\app-1.1.0\resources\app.asar\src\pane.js:788

TypeError: Cannot convert undefined or null to object
  at Object.module.exports.generateTags (C:\Users\ainstushar\.atom\packages\atom-ctags\lib\ctags-cache.coffee:78:24)
  at C:\Users\ainstushar\.atom\packages\atom-ctags\lib\file-view.coffee:13:21
  at Emitter.module.exports.Emitter.emit (C:\Users\ainstushar\AppData\Local\atom\app-1.1.0\resources\app.asar\node_modules\event-kit\lib\emitter.js:86:11)
  at TextBuffer.module.exports.TextBuffer.saveAs (C:\Users\ainstushar\AppData\Local\atom\app-1.1.0\resources\app.asar\node_modules\text-buffer\lib\text-buffer.js:1035:20)
  at TextBuffer.module.exports.TextBuffer.save (C:\Users\ainstushar\AppData\Local\atom\app-1.1.0\resources\app.asar\node_modules\text-buffer\lib\text-buffer.js:1002:19)
  at TextEditor.module.exports.TextEditor.save (C:\Users\ainstushar\AppData\Local\atom\app-1.1.0\resources\app.asar\src\text-editor.js:519:26)
  at Pane.module.exports.Pane.saveItem (C:\Users\ainstushar\AppData\Local\atom\app-1.1.0\resources\app.asar\src\pane.js:529:18)
  at Pane.module.exports.Pane.saveActiveItem (C:\Users\ainstushar\AppData\Local\atom\app-1.1.0\resources\app.asar\src\pane.js:512:19)
  at Workspace.module.exports.Workspace.saveActivePaneItem (C:\Users\ainstushar\AppData\Local\atom\app-1.1.0\resources\app.asar\src\workspace.js:560:35)
  at atom-workspace.atom.commands.add.core:save (C:\Users\ainstushar\AppData\Local\atom\app-1.1.0\resources\app.asar\src\workspace-element.js:270:30)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (C:\Users\ainstushar\AppData\Local\atom\app-1.1.0\resources\app.asar\src\command-registry.js:243:29)
  at C:\Users\ainstushar\AppData\Local\atom\app-1.1.0\resources\app.asar\src\command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (C:\Users\ainstushar\AppData\Local\atom\app-1.1.0\resources\app.asar\node_modules\atom-keymap\lib\keymap-manager.js:528:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (C:\Users\ainstushar\AppData\Local\atom\app-1.1.0\resources\app.asar\node_modules\atom-keymap\lib\keymap-manager.js:351:22)
  at HTMLDocument.module.exports.WindowEventHandler.handleDocumentKeydown (C:\Users\ainstushar\AppData\Local\atom\app-1.1.0\resources\app.asar\src\window-event-handler.js:97:20)
````

Has this issue been resolved?

**Comment by juanmirocks** [comment]
To add to the discussion, I got the following error **even if I had ctags disabled** (it may not be the same issue
```
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.12.5
**Electron Version**: 1.3.9
**System**: Mac OS X 10.12.1
**Thrown From**: [atom-ctags](https://github.com/yongkangchen/atom-ctags) package, v5.0.0


### Stack Trace

Uncaught TypeError: Cannot convert undefined or null to object

```
At /Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:1030

TypeError: Cannot convert undefined or null to object
    at Object.generateTags (/Users/juanmirocks/.atom/packages/atom-ctags/lib/ctags-cache.coffee:79:24)
    at /Users/juanmirocks/.atom/packages/atom-ctags/lib/file-view.coffee:13:21
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:129:28)
    at TextBuffer.module.exports.TextBuffer.saveAs (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:1154:27)
    at TextBuffer.module.exports.TextBuffer.save (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:1124:19)
    at TextEditor.module.exports.TextEditor.save (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:871:26)
    at Pane.module.exports.Pane.saveItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:738:18)
    at Pane.saveItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:3:59)
    at Pane.module.exports.Pane.saveActiveItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:721:19)
    at Workspace.module.exports.Workspace.saveActivePaneItem (/Applications/Atom.app/Contents/Resources/app.asar/src/workspace.js:693:35)
    at atom-workspace.core:save (/Applications/Atom.app/Contents/Resources/app.asar/src/register-default-commands.js:222:32)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:259:29)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:59
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:587:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:382:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:106:36)
    at HTMLDocument.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:3:59)
```

### Commands

```
     -0:27.4.0 core:cancel (atom-text-editor.editor.mini.is-focused)
     -0:26.7.0 intentions:highlight (atom-text-editor.editor.is-focused)
     -0:24.8.0 editor:consolidate-selections (atom-text-editor.editor.mini.is-focused)
     -0:24.8.0 core:cancel (atom-text-editor.editor.mini.is-focused)
     -0:23.7.0 core:save (atom-text-editor.editor.is-focused)
  3x -0:23.1.0 core:move-up (atom-text-editor.editor.is-focused)
     -0:22.1.0 editor:consolidate-selections (atom-text-editor.editor.is-focused)
     -0:22.1.0 core:cancel (atom-text-editor.editor.is-focused)
  2x -0:20.9.0 core:save (atom-text-editor.editor.is-focused)
     -0:06.7.0 editor:consolidate-selections (atom-text-editor.editor.is-focused)
     -0:06.7.0 core:cancel (atom-text-editor.editor.is-focused)
     -0:06.0 core:close (atom-text-editor.editor.is-focused)
     -0:05.3.0 fuzzy-finder:toggle-file-finder (atom-workspace.workspace.scrollbars-visible-when-scrolling.seti-ui-no-icons.theme-one-dark-syntax.theme-one-dark-ui)
     -0:04.1.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:00.4.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:00.1.0 core:save (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "customFileTypes": {
      "source.ini": [
        ".buckconfig",
        ".flowconfig"
      ],
      "source.json": [
        ".arcconfig",
        "BUCK.autodeps"
      ],
      "source.python": [
        "BUCK"
      ]
    },
    "disabledPackages": [
      "scala-worksheet",
      "linter-pylint",
      "react",
      "symbols-view",
      "atom-ctags"
    ],
    "ignoredNames": [
      ".git",
      ".hg",
      ".svn",
      ".DS_Store",
      "._*",
      "Thumbs.db",
      ".eggs",
      "target",
      "build",
      "dist",
      "*.egg-info",
      ".cache/",
      "__pycache__",
      "resources/*",
      "corpora/*",
      "*.log"
    ],
    "packagesWithKeymapsDisabled": [
      "tree-view",
      "java-generator",
      "tool-bar"
    ],
    "projectHome": "$HCK",
    "telemetryConsent": "limited"
  },
  "atom-ctags": {
    "autoBuildTagsWhenActive": true,
    "cmdArgs": "--exclude=*.egg* --exclude=resources --exclude=data"
  }
}
```

### Installed Packages

```coffee
# User
advanced-open-file, v0.16.4 (inactive)
atom-beautify, v0.29.13 (active)
atom-ctags, v5.0.0 (inactive)
autocomplete-python, v1.8.12 (active)
browser-plus, v0.0.86 (active)
color-picker, v2.2.3 (active)
custom-title, v1.0.1 (active)
Ensime, v0.39.0 (active)
file-icons, v1.7.25 (active)
git-plus, v5.25.5 (active)
git-time-machine, v1.5.4 (inactive)
highlight-selected, v0.11.2 (active)
hyperclick, vundefined (active)
intentions, v1.1.2 (active)
language-babel, v2.48.5 (active)
language-docker, v1.1.7 (active)
language-nginx, v0.6.2 (active)
language-scala, v1.1.8 (active)
linter, v1.11.18 (active)
linter-csslint, v1.3.3 (active)
linter-htmlhint, v1.3.1 (active)
linter-javac, v1.9.4 (active)
linter-jshint, v3.0.1 (active)
linter-pep8, v1.3.2 (active)
linter-scalac, v1.4.2 (active)
markdown-pdf, v1.5.0 (inactive)
merge-conflicts, v1.4.4 (active)
minimap, v4.25.6 (active)
minimap-find-and-replace, v4.5.1 (active)
minimap-git-diff, v4.3.1 (active)
minimap-highlight-selected, v4.4.0 (active)
minimap-pigments, v0.2.1 (active)
pigments, v0.37.0 (active)
project-manager, v3.3.3 (active)
remote-sync, v4.1.5 (active)
split-diff, v1.0.6 (inactive)
wordcount, v2.8.0 (active)
atom-dark-syntax, v0.27.0 (inactive)
atom-dark-ui, v0.52.0 (inactive)
atom-light-syntax, v0.28.0 (inactive)
atom-light-ui, v0.45.0 (inactive)
base16-tomorrow-dark-theme, v1.3.0 (inactive)
base16-tomorrow-light-theme, v1.3.0 (inactive)
one-dark-ui, v1.6.2 (active)
one-light-ui, v1.6.2 (inactive)
one-dark-syntax, v1.5.0 (active)
one-light-syntax, v1.5.0 (inactive)
solarized-dark-syntax, v1.0.5 (inactive)
solarized-light-syntax, v1.0.5 (inactive)
about, v1.7.0 (active)
archive-view, v0.62.0 (active)
autocomplete-atom-api, v0.10.0 (active)
autocomplete-css, v0.13.1 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.31.4 (active)
autocomplete-snippets, v1.11.0 (active)
autoflow, v0.27.0 (inactive)
autosave, v0.23.1 (active)
background-tips, v0.26.1 (active)
bookmarks, v0.42.0 (active)
bracket-matcher, v0.82.2 (active)
command-palette, v0.39.0 (inactive)
deprecation-cop, v0.54.1 (active)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
exception-reporting, v0.40.0 (active)
find-and-replace, v0.202.2 (active)
fuzzy-finder, v1.4.0 (active)
git-diff, v1.1.0 (active)
go-to-line, v0.31.0 (active)
grammar-selector, v0.48.2 (active)
image-view, v0.60.0 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.5.0 (active)
link, v0.31.2 (inactive)
markdown-preview, v0.158.8 (active)
metrics, v1.1.2 (active)
notifications, v0.65.1 (active)
open-on-github, v1.2.1 (inactive)
package-generator, v1.0.1 (inactive)
settings-view, v0.243.1 (active)
snippets, v1.0.4 (active)
spell-check, v0.68.4 (active)
status-bar, v1.4.1 (active)
styleguide, v0.47.2 (active)
symbols-view, v0.113.1 (inactive)
tabs, v0.103.0 (active)
timecop, v0.33.2 (active)
tree-view, v0.210.0 (active)
update-package-dependencies, v0.10.0 (active)
welcome, v0.35.1 (active)
whitespace, v0.35.0 (active)
wrap-guide, v0.38.2 (active)
language-c, v0.54.0 (active)
language-clojure, v0.22.1 (active)
language-coffee-script, v0.48.0 (active)
language-csharp, v0.13.0 (active)
language-css, v0.40.1 (active)
language-gfm, v0.88.0 (active)
language-git, v0.15.0 (active)
language-go, v0.43.0 (active)
language-html, v0.47.1 (active)
language-hyperlink, v0.16.1 (active)
language-java, v0.24.0 (active)
language-javascript, v0.122.0 (active)
language-json, v0.18.3 (active)
language-less, v0.29.6 (active)
language-make, v0.22.2 (active)
language-mustache, v0.13.0 (active)
language-objective-c, v0.15.1 (active)
language-perl, v0.37.0 (active)
language-php, v0.37.3 (active)
language-property-list, v0.8.0 (active)
language-python, v0.45.1 (active)
language-ruby, v0.70.2 (active)
language-ruby-on-rails, v0.25.1 (active)
language-sass, v0.57.0 (active)
language-shellscript, v0.23.0 (active)
language-source, v0.9.0 (active)
language-sql, v0.25.0 (active)
language-text, v0.7.1 (active)
language-todo, v0.29.1 (active)
language-toml, v0.18.1 (active)
language-xml, v0.34.12 (active)
language-yaml, v0.27.1 (active)

# Dev
No dev packages
```
