### ISSUE TITLE
Uncaught TypeError: Arguments to path.join must be strings

### ISSUE THREAD

**Issue by averrin** [yongkangchen/atom-ctags#98]
Ctrl+r in js file. 

```
Uncaught TypeError: Arguments to path.join must be strings
path.js:449
Hide Stack Trace
TypeError: Arguments to path.join must be strings
  at Object.posix.join (path.js:449:13)
  at module.exports (/home/user/.atom/packages/atom-ctags/lib/tag-generator.coffee:38:19)
  at Object.module.exports.generateTags (/home/user/.atom/packages/atom-ctags/lib/ctags-cache.coffee:85:5)
  at Object.module.exports.getOrCreateTags (/home/user/.atom/packages/atom-ctags/lib/ctags-cache.coffee:98:6)
  at FileView.module.exports.FileView.populate (/home/user/.atom/packages/atom-ctags/lib/file-view.coffee:101:17)
  at FileView.module.exports.FileView.toggle (/home/user/.atom/packages/atom-ctags/lib/file-view.coffee:41:8)
  at atom-text-editor.atom.commands.add.atom-ctags:toggle-file-symbols (/home/user/.atom/packages/atom-ctags/lib/main.coffee:53:62)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app.asar/src/command-registry.js:238:29)
  at /usr/share/atom/resources/app.asar/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/usr/share/atom/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:520:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/usr/share/atom/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:355:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/usr/share/atom/resources/app.asar/src/window-event-handler.js:178:20)
```

**Comment by yongkangchen** [comment]
I guess your js file is not exist in project path?

**Comment by averrin** [comment]
@yongkangchen hmm, yes, its file opened witj ctrl+o from other folder
